T1	Protein	interferon regulatory factor 4
T2	Protein	bcr
T3	Protein	abl
T5	Protein	IRF-4
*	Equiv T1 T5
E1	Negative_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Regulation Theme:T1
E4	Regulation Theme:E5
E5	Gene_expression Theme:T1
E6	Regulation Theme:E7
E7	Gene_expression Theme:T1
E8	Regulation Theme:E9
E9	Transcription Theme:T1
E10	Gene_expression Theme:T1
E11	Positive_regulation Theme:E12
E12	Positive_regulation Theme:T1
E13	Gene_expression Theme:T1
E14	Gene_expression Theme:T1
E15	Negative_regulation Theme:T1
E16	Negative_regulation Theme:E17
E17	Gene_expression Theme:T1
M1	Negation E3
M2	Speculation E4
M3	Negation E10
M4	Negation E13
M5	Speculation E16
