T1	Protein	perforin
T2	Protein	granzyme B
T3	Protein	IFN-gamma
T4	Protein	T-bet
T5	Protein	Eomes
T7	Protein	Tbx21
T10	Protein	CD8
T13	Protein	Prf1
T14	Protein	GzmB
T17	Protein	Eomes-VP16
T18	Protein	Eo-VP16
T19	Protein	GFP
T20	Protein	Granzyme B
*	Equiv T17 T18
E1	Regulation Cause:T4 Theme:E2
E3	Regulation Cause:T5 Theme:E2
E4	Regulation Cause:T4 Theme:E5
E6	Regulation Cause:T5 Theme:E5
E7	Regulation Cause:T4 Theme:E8
E9	Regulation Cause:T5 Theme:E8
E2	Gene_expression Theme:T1
E5	Gene_expression Theme:T2
E8	Gene_expression Theme:T3
E10	Gene_expression Theme:T3
E11	Negative_regulation Theme:T4
E12	Gene_expression Theme:T3
E13	Transcription Theme:T13
E14	Transcription Theme:T14
E15	Negative_regulation Theme:T4
E16	Gene_expression Theme:T17
E17	Gene_expression Theme:T20
E18	Gene_expression Theme:T3
E19	Gene_expression Theme:T3
M1	Speculation E10
M2	Speculation E12
M3	Speculation E13
M4	Speculation E14
M5	Speculation E17
M6	Speculation E18
M7	Speculation E19
