T1	Protein	Foxp3
T5	Protein	CD4
T12	Protein	CD25
T17	Entity	carboxyl-terminal forkhead (FKH) domain
T19	Entity	nuclear
E1	Positive_regulation Theme:T1
E2	Negative_regulation Site:T17 Theme:T1
E3	Positive_regulation CSite:T17 Cause:T1 Theme:E4
E5	Positive_regulation CSite:T17 Cause:T1 Theme:E6
E4	Localization Theme:T1 ToLoc:T19
E6	Binding Theme:T1
E7	Positive_regulation Theme:E8
E8	Gene_expression Theme:T1
