T1	Protein	granulocyte-macrophage colony-stimulating factor
T2	Protein	E-selectin
T4	Protein	GM-CSF
T7	Protein	vascular cell adhesion molecule-1
T8	Protein	VCAM-1
T10	Protein	tumor necrosis factor (TNF)-alpha
T11	Protein	DNasel
*	Equiv T1 T4
*	Equiv T7 T8
T21	Entity	promoter
E1	Regulation Theme:E4
E2	Regulation Theme:E3
E3	Gene_expression Theme:T2
E4	Gene_expression Theme:T1
E5	Negative_regulation Theme:E8
E6	Negative_regulation Theme:E7
E7	Transcription Theme:T1
E8	Gene_expression Theme:T1
E9	Negative_regulation Theme:E12
E10	Negative_regulation Theme:E11
E11	Gene_expression Theme:T2
E12	Gene_expression Theme:T7
E13	Positive_regulation Site:T21 Theme:T2
E14	Positive_regulation Cause:T10 Theme:E15
E15	Gene_expression Theme:T2
E16	Negative_regulation Theme:E14
M1	Negation E9
M2	Negation E13
