T1	Protein	granulocyte-macrophage colony-stimulating factor
T2	Protein	Granulocyte-macrophage colony-stimulating factor
T3	Protein	GM-CSF
T9	Protein	DNase I
T11	Protein	Tax
T14	Protein	interleukin 3
*	Equiv T2 T3
T26	Entity	proximal promoter
T30	Entity	kappaB element
E1	Negative_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Gene_expression Theme:T2
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T2
E6	Negative_regulation Theme:E7
E7	Transcription Theme:T2
E8	Binding Site:T26 Theme:T2
E9	Negative_regulation Theme:E10
E10	Positive_regulation Theme:T2
E11	Regulation Theme:T14
E12	Positive_regulation CSite:T30 Cause:T2 Theme:E13
E13	Positive_regulation Theme:T2
E14	Negative_regulation Theme:T2
E15	Positive_regulation Theme:E16
E16	Gene_expression Theme:T2
M1	Negation E11
