T1	Protein	Tpl-2
T2	Protein	IL-2
T10	Protein	Raf1
T13	Protein	MEK1
T14	Protein	MEK2
T23	Protein	Bcl-2
T24	Protein	Bcl-X(L)
T30	Entity	promoter
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T2
E3	Positive_regulation Cause:T1 Theme:E4
E4	Gene_expression Theme:T2
E5	Positive_regulation Cause:T1 Site:T30 Theme:T2
E6	Negative_regulation Theme:E5
E7	Positive_regulation Theme:E5
E8	Positive_regulation Theme:E9
E9	Positive_regulation Cause:T1 Site:T30 Theme:T2
E10	Positive_regulation Site:T30 Theme:T2
E11	Regulation Theme:E10
E12	Positive_regulation Cause:T1 Site:T30 Theme:T2
E13	Negative_regulation Theme:E12
E14	Negative_regulation Theme:T1
E15	Negative_regulation Theme:T13
E16	Positive_regulation Site:T30 Theme:T2
E17	Regulation Theme:E16
E18	Positive_regulation Cause:T1 Site:T30 Theme:T2
E19	Negative_regulation Theme:E18
E20	Negative_regulation Theme:E18
