T1	Protein	PAF receptor
T2	Protein	platelet-activating factor receptor
T3	Protein	PAFR
T10	Protein	chloramphenicol acetyltransferase
T11	Protein	CAT
*	Equiv T2 T3
*	Equiv T10 T11
E1	Positive_regulation Theme:T1
E2	Transcription Theme:T2
E3	Positive_regulation Theme:E2
E4	Positive_regulation Theme:T2
E5	Gene_expression Theme:T2
E6	Gene_expression Theme:T2
E7	Positive_regulation Theme:E8
E8	Gene_expression Theme:T2
M1	Negation E4
