T1	Protein	alpha2 integrin
T3	Protein	c-fos
T4	Protein	c-jun
T6	Protein	MAPK kinase 1
E1	Regulation Theme:T1
E2	Positive_regulation Theme:E1
E3	Positive_regulation Theme:E6
E4	Positive_regulation Theme:E5
E5	Binding Theme:T3
E6	Binding Theme:T4
E7	Positive_regulation Theme:E9
E8	Positive_regulation Theme:E9
E9	Regulation Theme:E10
E10	Gene_expression Theme:T1
E11	Negative_regulation Theme:T6
E12	Negative_regulation Theme:E13
E13	Gene_expression Theme:T1
E14	Gene_expression Theme:T1
E15	Positive_regulation Theme:E14
