T1	Protein	IkappaB-alpha
T4	Protein	tumor necrosis factor-alpha
T5	Protein	TNF-alpha
T7	Protein	vascular cell adhesion molecule-1
T8	Protein	VCAM-1
T9	Protein	intercellular adhesion molecule-1
T10	Protein	ICAM-1
T11	Protein	E-selectin
T12	Protein	monocyte chemoattractant protein 1
T13	Protein	MCP-1
T14	Protein	growth-related activity-alpha
T15	Protein	GRO-alpha
T22	Protein	P-selectin
*	Equiv T14 T15
*	Equiv T12 T13
*	Equiv T7 T8
*	Equiv T9 T10
*	Equiv T4 T5
E1	Gene_expression Theme:T1
E2	Positive_regulation Theme:E1
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Positive_regulation Theme:E4
E6	Gene_expression Theme:T1
E7	Positive_regulation Theme:E6
E8	Negative_regulation Cause:E7 Theme:E10
E9	Positive_regulation Cause:T4 Theme:E10
E10	Protein_catabolism Theme:T1
E11	Negative_regulation Cause:E6 Theme:E20
E12	Negative_regulation Cause:E6 Theme:E22
E13	Negative_regulation Cause:E6 Theme:E24
E14	Negative_regulation Cause:E6 Theme:E19
E15	Negative_regulation Cause:E6 Theme:E32
E16	Negative_regulation Cause:E6 Theme:E31
E17	Negative_regulation Cause:E6 Theme:E23
E18	Negative_regulation Cause:E6 Theme:E21
E19	Positive_regulation Theme:E25
E20	Positive_regulation Theme:E30
E21	Positive_regulation Theme:E29
E22	Positive_regulation Theme:E27
E23	Positive_regulation Theme:E28
E24	Positive_regulation Theme:E26
E25	Transcription Theme:T7
E26	Gene_expression Theme:T11
E27	Gene_expression Theme:T7
E28	Transcription Theme:T9
E29	Transcription Theme:T11
E30	Gene_expression Theme:T9
E31	Positive_regulation Cause:T4 Theme:E34
E32	Positive_regulation Cause:T4 Theme:E33
E33	Transcription Theme:T14
E34	Transcription Theme:T12
E35	Negative_regulation Theme:E36
E36	Localization Theme:T12
E37	Localization Theme:T14
E38	Gene_expression Theme:T1
E39	Positive_regulation Theme:E38
E40	Positive_regulation Theme:E41
E41	Gene_expression Theme:T1
E42	Negative_regulation Theme:E43
E43	Positive_regulation Theme:T11
E44	Gene_expression Theme:T1
E45	Positive_regulation Theme:E44
M1	Speculation E3
M2	Negation E37
