T1	Protein	interleukin-8
T2	Protein	eosinophil granule major basic protein
T4	Protein	MBP
T5	Protein	interleukin (IL)-8
T7	Protein	IL-8
T10	Protein	eosinophil cationic protein
T11	Protein	eosinophil peroxidase
T19	Protein	macrophage inflammatory protein (MIP)-1alpha
T20	Protein	MIP-1beta
*	Equiv T2 T4
E1	Gene_expression Theme:T1
E2	Positive_regulation Cause:T2 Theme:E3
E3	Gene_expression Theme:T5
E4	Positive_regulation Cause:T2 Theme:E5
E5	Localization Theme:T7
E6	Localization Theme:T7
E7	Positive_regulation Cause:T2 Theme:E6
E8	Gene_expression Theme:T7
E9	Positive_regulation Cause:T2 Theme:E10
E10	Positive_regulation Theme:T7
E11	Negative_regulation Theme:E9
E12	Positive_regulation Theme:T7
E13	Positive_regulation Cause:T2 Theme:T20
E14	Positive_regulation Cause:T2 Theme:T19
E15	Positive_regulation Cause:T2 Theme:E17
E16	Positive_regulation Cause:T2 Theme:E18
E17	Localization Theme:T19
E18	Localization Theme:T20
E19	Localization Theme:T7
E20	Localization Theme:T7
E21	Positive_regulation Cause:T2 Theme:E22
E22	Localization Theme:T7
M1	Speculation E2
M2	Negation E15
M3	Negation E16
