T1	Protein	junB
T2	Protein	interleukin-6
T5	Protein	IL-6
T12	Protein	JunB
*	Equiv T2 T5
T32	Entity	nuclear
E1	Regulation Theme:E2
E2	Transcription Theme:T1
E3	Positive_regulation Cause:T2 Theme:E2
E4	Transcription Theme:T1
E5	Regulation Theme:E4
E6	Positive_regulation Cause:T2 Theme:T1
E7	Positive_regulation Cause:T2 Theme:T1
E8	Regulation Cause:T2 Theme:T1
E9	Positive_regulation Cause:E8 Theme:E10
E10	Localization AtLoc:T32 Theme:T12
E11	Positive_regulation Cause:E13 Theme:T1
E12	Positive_regulation Cause:E13 Theme:T12
E13	Positive_regulation Cause:T2 Theme:E14
E14	Transcription Theme:T1
E15	Regulation Theme:E16
E16	Positive_regulation Cause:T2 Theme:E17
E17	Transcription Theme:T1
E18	Negative_regulation Theme:E19
E19	Transcription Theme:T1
E20	Negative_regulation Theme:E21
E21	Transcription Theme:T1
E22	Regulation Theme:E21
E23	Regulation Cause:T2 Theme:E24
E24	Transcription Theme:T1
E25	Positive_regulation Theme:E23
M1	Speculation E4
M2	Speculation E5
M3	Negation E18
M4	Negation E22
