T1	Protein	IL-2
T4	Protein	IFN-beta
T8	Protein	P53
T9	Protein	Rb
T10	Protein	Bcl-xL
T12	Protein	signal transducers and activators of transcription (STAT) 2
T13	Protein	STAT2
T22	Entity	tyrosine
T25	Entity	nucleus
E1	Negative_regulation Theme:T1
E2	Negative_regulation Theme:T1
E3	Negative_regulation Theme:T1
E4	Negative_regulation Theme:T1
E5	Positive_regulation Cause:T1 Theme:E10
E6	Positive_regulation Cause:T1 Theme:E9
E7	Positive_regulation Cause:T1 Theme:E8
E8	Gene_expression Theme:T8
E9	Gene_expression Theme:T10
E10	Gene_expression Theme:T9
E11	Positive_regulation Theme:E13
E12	Positive_regulation Theme:E14
E13	Phosphorylation Site:T22 Theme:T12
E14	Localization Theme:T12 ToLoc:T25
E15	Gene_expression Theme:T13
E16	Positive_regulation Theme:E15
