T1	Protein	c-fos
T2	Protein	c-jun
T5	Protein	c-Fos
T6	Protein	c-Jun
T9	Protein	CD3epsilon
T10	Protein	PHA
T22	Protein	serum response factor
T23	Protein	Elk-1
T30	Entity	promoter
T45	Entity	DNA sequence motifs
E1	Negative_regulation Theme:E3
E2	Negative_regulation Theme:E4
E3	Positive_regulation Theme:T2
E4	Positive_regulation Theme:T1
E5	Binding Site:T30 Theme:T1
E6	Binding Site:T30 Theme:T2
E7	Positive_regulation Theme:T6
E8	Positive_regulation Theme:T5
E9	Negative_regulation Theme:E8
E10	Negative_regulation Theme:E7
E11	Regulation Theme:E13
E12	Regulation Theme:E14
E13	Transcription Theme:T2
E14	Transcription Theme:T1
E15	Binding Theme:T9
E16	Positive_regulation Theme:E17
E17	Gene_expression Theme:T5
E18	Gene_expression Theme:T5
E19	Gene_expression Theme:T6
E20	Negative_regulation Theme:E18
E21	Negative_regulation Theme:E19
E22	Negative_regulation Theme:E25
E23	Negative_regulation Theme:E24
E24	Transcription Theme:T2
E25	Transcription Theme:T1
E26	Gene_expression Theme:T1
E27	Positive_regulation Theme:E29
E28	Positive_regulation Theme:E30
E29	Binding Site:T45 Theme:T2
E30	Binding Site:T45 Theme:T1
E31	Positive_regulation Theme:E30
E32	Regulation Theme:E35
E33	Regulation Theme:E34
E34	Positive_regulation Theme:T1
E35	Positive_regulation Theme:T2
M1	Speculation E11
M2	Speculation E12
M3	Speculation E13
M4	Speculation E14
M5	Negation E21
