T1	Protein	p40
T2	Protein	latent membrane protein 1
T3	Protein	LMP1
T5	Protein	p35
*	Equiv T2 T3
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Gene_expression Theme:T2
E4	Transcription Theme:T1
E5	Transcription Theme:T5
E6	Positive_regulation Theme:E7
E7	Gene_expression Theme:T1
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T1
E10	Positive_regulation Theme:E11
E11	Gene_expression Theme:T2
