T1	Protein	CIITA
T2	Protein	RFX5
T6	Protein	GAL4
T8	Protein	interferon gamma
T32	Entity	DNA binding domain
E1	Binding Theme:T1 Theme2:T2
E2	Negative_regulation Theme:T1
E3	Negative_regulation Theme:T2
E4	Binding Theme:T1
E5	Gene_expression Theme:T1
E6	Positive_regulation Theme:E5
E7	Negative_regulation Theme:T1
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T1
E10	Binding Theme:T2 Theme2:T1
E11	Binding Theme:T2 Theme2:T1
E12	Binding Site:T32 Theme:T2
M1	Negation E4
