T1	Protein	CD4
T6	Protein	interleukin-2
T8	Protein	gp120
T9	Protein	p56lck
T10	Protein	p59fyn
T15	Entity	epitopes
E1	Binding Theme:T1
E2	Positive_regulation Theme:T1
E3	Binding Site:T15 Theme:T1
E4	Positive_regulation Theme:T1
E5	Positive_regulation Theme:E6
E6	Gene_expression Theme:T6
E7	Positive_regulation Theme:E11
E8	Positive_regulation Theme:E12
E9	Positive_regulation Cause:T8 Theme:E12
E10	Positive_regulation Cause:T8 Theme:E11
E11	Positive_regulation Theme:T10
E12	Positive_regulation Theme:T9
