T1	Protein	glucocorticoid receptor
T3	Protein	GR
*	Equiv T1 T3
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Negative_regulation Theme:T1
E6	Positive_regulation Theme:T1
E7	Positive_regulation Theme:T1
E8	Transcription Theme:T1
E9	Negative_regulation Theme:E8
E10	Positive_regulation Cause:T1 Theme:E11
E11	Gene_expression Theme:T1
E12	Regulation Theme:E13
E13	Gene_expression Theme:T1
E14	Positive_regulation Theme:E12
E15	Negative_regulation Theme:E13
E16	Positive_regulation Theme:E13
E17	Regulation Theme:E15
E18	Regulation Theme:E16
E19	Regulation Theme:T1
E20	Regulation Theme:T1
E21	Regulation Theme:E22
E22	Transcription Theme:T1
M1	Speculation E3
M2	Negation E14
M3	Negation E17
M4	Negation E18
M5	Negation E19
M6	Negation E20
