T1	Protein	PPARgamma
T2	Protein	adipocyte fatty acid binding protein
T3	Protein	peroxisome-proliferator activated receptor gamma
T7	Protein	aP2
*	Equiv T1 T3
*	Equiv T2 T7
E1	Positive_regulation Theme:T3
E2	Positive_regulation Cause:E1 Theme:E3
E3	Gene_expression Theme:T2
E4	Positive_regulation Cause:T3 Theme:E5
E5	Gene_expression Theme:T2
E6	Gene_expression Theme:T3
E7	Positive_regulation Theme:T3
E8	Positive_regulation Theme:T3
E9	Positive_regulation Theme:E10
E10	Positive_regulation Theme:T2
E11	Positive_regulation Theme:T3
