T1	Protein	I kappa B alpha
T2	Protein	I kappa B beta
T8	Protein	TNF-alpha
E1	Protein_catabolism Theme:T2
E2	Protein_catabolism Theme:T1
E3	Positive_regulation Theme:T2
E4	Positive_regulation Theme:T1
E5	Positive_regulation Theme:E6
E6	Negative_regulation Theme:T2
E7	Gene_expression Theme:T1
E8	Gene_expression Theme:T2
E9	Negative_regulation Theme:T8
E10	Phosphorylation Theme:T1
E11	Gene_expression Theme:T1
E12	Positive_regulation Cause:E15 Theme:E10
E13	Protein_catabolism Theme:T1
E14	Positive_regulation Theme:E13
E15	Negative_regulation Theme:E13
E16	Phosphorylation Theme:T1
E17	Protein_catabolism Theme:T1
E18	Positive_regulation Theme:E17
E19	Positive_regulation Theme:E16
E20	Gene_expression Theme:T1
M1	Negation E8
