T1	Protein	NFATp
T2	Protein	NFATc
T4	Protein	Fc gamma RIIIA
E1	Positive_regulation Theme:T2
E2	Positive_regulation Theme:T1
E3	Gene_expression Theme:T1
E4	Gene_expression Theme:T2
E5	Regulation Theme:E1
E6	Regulation Theme:E4
E7	Regulation Theme:E3
E8	Regulation Theme:E2
E9	Regulation Theme:T1
E10	Gene_expression Theme:T2
E11	Positive_regulation Theme:T2
E12	Positive_regulation Theme:E11
E13	Gene_expression Theme:T2
E14	Regulation Theme:T1
E15	Regulation Theme:T2
E16	Gene_expression Theme:T1
E17	Gene_expression Theme:T2
E18	Positive_regulation Theme:T2
E19	Positive_regulation Theme:T1
E20	Gene_expression Theme:T1
E21	Gene_expression Theme:T2
E22	Regulation Theme:E18
E23	Regulation Theme:E19
E24	Regulation Theme:E21
E25	Regulation Theme:E20
E26	Positive_regulation Cause:E22 Theme:E30
E27	Positive_regulation Cause:E23 Theme:E30
E28	Positive_regulation Cause:E25 Theme:E30
E29	Positive_regulation Cause:E24 Theme:E30
E30	Positive_regulation Theme:T1
E31	Positive_regulation Cause:E27 Theme:E35
E32	Positive_regulation Cause:E29 Theme:E35
E33	Positive_regulation Cause:E26 Theme:E35
E34	Positive_regulation Cause:E28 Theme:E35
E35	Transcription Theme:T2
M1	Negation E10
M2	Negation E13
