T1	Protein	catalase
T2	Protein	xanthine oxidase
T3	Protein	intercellular adhesion molecule-1
T4	Protein	ICAM-1
T5	Protein	P-selectin
T8	Protein	E-selectin
T9	Protein	activator protein-1
*	Equiv T3 T4
E1	Regulation Theme:E3
E2	Regulation Theme:E4
E3	Gene_expression Theme:T3
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T5
E6	Gene_expression Theme:T8
E7	Gene_expression Theme:T5
E8	Gene_expression Theme:T3
