T1	Protein	Tax
T6	Protein	Fos
T7	Protein	Jun
E1	Gene_expression Theme:T1
E2	Gene_expression Theme:T1
E3	Gene_expression Theme:T1
E4	Gene_expression Theme:T1
E5	Gene_expression Theme:T1
E6	Positive_regulation Theme:T6
E7	Positive_regulation Theme:T7
E8	Negative_regulation Cause:E5 Theme:E7
E9	Negative_regulation Cause:E5 Theme:E6
E10	Regulation Theme:E11
E11	Gene_expression Theme:T1
M1	Negation E8
M2	Negation E9
