T1	Protein	Interleukin-3
T3	Protein	IL-3
T6	Protein	Oct-1
T7	Protein	IL-2
*	Equiv T1 T3
T13	Entity	ACT-1-activating region
T19	Entity	ARRE-1 site
E1	Gene_expression Theme:T1
E2	Gene_expression Theme:T1
E3	Regulation Theme:T1
E4	Binding Site:T13 Theme:T1
E5	Positive_regulation Theme:E6
E6	Gene_expression Theme:T1
E7	Binding Site:T13 Theme:T1
E8	Positive_regulation Site:T19 Theme:T7
E9	Positive_regulation Theme:E12
E10	Positive_regulation Theme:E11
E11	Gene_expression Theme:T1
E12	Gene_expression Theme:T7
M1	Speculation E9
M2	Speculation E10
