T1	Protein	tissue factor
T2	Protein	Tissue factor
T3	Protein	TF
*	Equiv T2 T3
T20	Entity	plasmalemmal
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Gene_expression Theme:T2
E4	Regulation Theme:E5
E5	Positive_regulation Theme:E6
E6	Gene_expression Theme:T2
E7	Negative_regulation Theme:E8
E8	Positive_regulation Theme:E9
E9	Positive_regulation Theme:T2
E10	Negative_regulation Theme:E12
E11	Localization Theme:T2 ToLoc:T20
E12	Positive_regulation Theme:E11
E13	Positive_regulation Theme:E14
E14	Positive_regulation Theme:T2
E15	Regulation Theme:E16
E16	Gene_expression Theme:T2
M1	Speculation E4
M2	Negation E7
M3	Negation E13
