T1	Protein	Thrombin
T2	Protein	CD69
T3	Protein	interleukin 2
T5	Protein	thrombin
T6	Protein	thrombin III
T16	Protein	thrombin receptor
T17	Protein	phytohemagglutinin
E1	Positive_regulation Theme:E5
E2	Positive_regulation Cause:T1 Theme:E6
E3	Positive_regulation Cause:T1 Theme:E5
E4	Positive_regulation Theme:E6
E5	Gene_expression Theme:T2
E6	Gene_expression Theme:T3
E7	Transcription Theme:T16
E8	Negative_regulation Theme:E9
E9	Transcription Theme:T16
E10	Positive_regulation Cause:T5 Theme:E15
E11	Positive_regulation Theme:E14
E12	Gene_expression Theme:T2
E13	Gene_expression Theme:T3
E14	Positive_regulation Theme:E13
E15	Positive_regulation Theme:E12
