T1	Protein	NFATx1
T10	Entity	nuclear
T23	Entity	intracellular
E1	Regulation Theme:E2
E2	Localization Theme:T1 ToLoc:T10
E3	Gene_expression Theme:T1
E4	Binding Theme:T1
E5	Positive_regulation Theme:E4
E6	Positive_regulation Theme:T1
E7	Negative_regulation Theme:E6
E8	Binding Theme:T1
E9	Positive_regulation Theme:E10
E10	Localization Theme:T1 ToLoc:T10
E11	Positive_regulation Theme:E10
E12	Regulation Theme:E13
E13	Localization AtLoc:T23 Theme:T1
E14	Regulation Theme:E12
M1	Negation E11
