T1	Protein	TNF-alpha
T2	Protein	Tumor necrosis factor alpha
*	Equiv T1 T2
E1	Positive_regulation Theme:E2
E2	Localization Theme:T2
E3	Positive_regulation Theme:E4
E4	Localization Theme:T2
E5	Positive_regulation Theme:E6
E6	Gene_expression Theme:T2
E7	Positive_regulation Theme:E8
E8	Localization Theme:T2
E9	Negative_regulation Theme:E10
E10	Localization Theme:T2
E11	Regulation Theme:E12
E12	Positive_regulation Theme:E13
E13	Localization Theme:T2
E14	Negative_regulation Theme:E15
E15	Positive_regulation Theme:E16
E16	Gene_expression Theme:T2
E17	Positive_regulation Theme:E18
E18	Gene_expression Theme:T2
E19	Positive_regulation Theme:E20
E20	Localization Theme:T2
E21	Positive_regulation Theme:E22
E22	Localization Theme:T2
M1	Negation E11
