T1	Protein	GM-CSF
T2	Protein	granulocyte-macrophage colony-stimulating factor
T6	Protein	p50
T7	Protein	p65
T13	Protein	KBF1
*	Equiv T1 T2
T26	Entity	enhancers
E1	Positive_regulation Theme:E3
E2	Gene_expression Theme:T2
E3	Regulation Theme:E2
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T2
E6	Positive_regulation Theme:E7
E7	Positive_regulation Theme:T2
E8	Positive_regulation Theme:T2
E9	Binding Site:T26 Theme:T2
E10	Binding Theme:T6
E11	Binding Theme:T6 Theme2:T7
E12	Binding Theme:T7
E13	Binding Theme:T6
E14	Positive_regulation Theme:E15
E15	Transcription Theme:T2
E16	Gene_expression Theme:T2
E17	Positive_regulation Theme:E16
M1	Negation E14
