T1	Protein	Tissue factor
T2	Protein	tissue factor
T3	Protein	TF
*	Equiv T2 T3
E1	Gene_expression Theme:T1
E2	Negative_regulation Theme:E1
E3	Gene_expression Theme:T2
E4	Positive_regulation Theme:E3
E5	Positive_regulation Theme:E4
E6	Negative_regulation Theme:E7
E7	Positive_regulation Theme:T2
E8	Regulation Theme:E9
E9	Positive_regulation Theme:T2
E10	Gene_expression Theme:T2
E11	Positive_regulation Theme:E10
E12	Negative_regulation Theme:E11
E13	Negative_regulation Theme:T2
E14	Positive_regulation Theme:E15
E15	Transcription Theme:T2
E16	Negative_regulation Theme:E14
E17	Negative_regulation Theme:E18
E18	Negative_regulation Theme:T2
E19	Negative_regulation Theme:E20
E20	Positive_regulation Theme:E21
E21	Gene_expression Theme:T2
E22	Positive_regulation Theme:E19
M1	Negation E8
M2	Speculation E22
