T1	Protein	tumor necrosis factor alpha
T3	Protein	TNF-alpha
T8	Protein	LPS-induced TNF-alpha factor
T9	Protein	LITAF
*	Equiv T8 T9
*	Equiv T1 T3
T25	Entity	DNA-binding domain
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E4
E4	Localization Theme:T1
E5	Gene_expression Theme:T1
E6	Regulation Theme:E5
E7	Regulation Theme:E8
E8	Transcription Theme:T1
E9	Binding Site:T25 Theme:T1
E10	Positive_regulation Theme:T8
E11	Regulation Theme:E10
E12	Negative_regulation Theme:E13
E13	Transcription Theme:T8
E14	Negative_regulation Cause:E12 Theme:E15
E15	Transcription Theme:T1
E16	Positive_regulation Theme:E17
E17	Transcription Theme:T8
E18	Regulation Cause:T8 Theme:E19
E19	Positive_regulation Theme:T1
E20	Regulation Cause:T8 Theme:E21
E21	Gene_expression Theme:T1
M1	Speculation E6
M2	Speculation E7
