T1	Protein	c-jun
T2	Protein	c-fos
T3	Protein	CD28
T5	Protein	phospholipase C gamma 1
T8	Protein	CD5
T9	Protein	CD7
T17	Protein	junB
E1	Regulation Theme:T2
E2	Regulation Theme:T1
E3	Binding Theme:T3
E4	Positive_regulation Cause:E5 Theme:T5
E5	Binding Theme:T3
E6	Binding Theme:T9
E7	Binding Theme:T8
E8	Binding Theme:T3
E9	Positive_regulation Cause:E7 Theme:E13
E10	Positive_regulation Cause:E8 Theme:E13
E11	Positive_regulation Theme:E13
E12	Positive_regulation Cause:E6 Theme:E13
E13	Positive_regulation Theme:T1
E14	Positive_regulation Cause:E8 Theme:E15
E15	Gene_expression Theme:T2
E16	Positive_regulation Cause:T3 Theme:E17
E17	Gene_expression Theme:T1
E18	Positive_regulation Theme:E16
E19	Regulation Theme:E16
E20	Positive_regulation Cause:T3 Theme:T1
E21	Positive_regulation Cause:E22 Theme:E20
E22	Regulation Theme:T1
E23	Gene_expression Theme:T17
E24	Gene_expression Theme:T1
E25	Binding Theme:T3
M1	Negation E9
M2	Negation E11
M3	Negation E12
M4	Negation E19
M5	Negation E21
M6	Speculation E21
