T1	Protein	vascular cell adhesion molecule-1
T2	Protein	VCAM-1
T3	Protein	interleukin (IL)-1 alpha
T5	Protein	IL-1 alpha
T6	Protein	IL-1 beta
T7	Protein	IL-4
T8	Protein	tumor necrosis factor
T9	Protein	TNF alpha
T10	Protein	E-selectin
T11	Protein	intercellular adhesion molecule-1
T12	Protein	IL-6
T13	Protein	IL-8
*	Equiv T8 T9
*	Equiv T1 T2
E1	Regulation Theme:E3
E2	Positive_regulation Theme:E3
E3	Gene_expression Theme:T1
E4	Negative_regulation Theme:E5
E5	Positive_regulation Cause:T3 Theme:E6
E6	Gene_expression Theme:T1
E7	Negative_regulation Theme:E16
E8	Negative_regulation Theme:E13
E9	Negative_regulation Theme:E15
E10	Negative_regulation Theme:E17
E11	Negative_regulation Theme:E14
E12	Regulation Theme:E4
E13	Positive_regulation Cause:T8 Theme:E6
E14	Positive_regulation Cause:T7 Theme:E6
E15	Positive_regulation Cause:T5 Theme:E6
E16	Positive_regulation Theme:E6
E17	Positive_regulation Cause:T6 Theme:E6
E18	Negative_regulation Theme:E24
E19	Negative_regulation Theme:E23
E20	Negative_regulation Theme:E22
E21	Negative_regulation Theme:E25
E22	Gene_expression Theme:T10
E23	Gene_expression Theme:T12
E24	Gene_expression Theme:T11
E25	Gene_expression Theme:T13
E26	Positive_regulation Theme:E27
E27	Gene_expression Theme:T1
E28	Positive_regulation Theme:E29
E29	Positive_regulation Theme:E30
E30	Gene_expression Theme:T1
E31	Negative_regulation Theme:E32
E32	Transcription Theme:T1
M1	Speculation E1
M2	Negation E12
M3	Negation E28
