T1	Protein	inducible nitric oxide synthase
T2	Protein	interferon-gamma
T4	Protein	IFN-gamma
T5	Protein	inducible NO synthase
T6	Protein	iNOS
*	Equiv T2 T4
*	Equiv T5 T6
T15	Entity	promoter regions
T20	Entity	promoter
E1	Regulation Cause:T2 Theme:T1
E2	Negative_regulation Theme:E4
E3	Negative_regulation Theme:E1
E4	Regulation Theme:T1
E5	Regulation Cause:T2 Site:T15 Theme:T5
E6	Regulation Site:T15 Theme:T5
E7	Positive_regulation Theme:E16
E8	Positive_regulation Cause:E18 Theme:E16
E9	Positive_regulation Cause:E18 Theme:E14
E10	Positive_regulation Cause:E17 Theme:E16
E11	Positive_regulation Cause:E17 Theme:E14
E12	Positive_regulation Theme:E14
E13	Regulation Cause:T2 Site:T20 Theme:T5
E14	Negative_regulation Theme:E15
E15	Regulation Site:T20 Theme:T5
E16	Negative_regulation Theme:E13
E17	Negative_regulation Theme:E19
E18	Negative_regulation Theme:E20
E19	Positive_regulation Theme:E21
E20	Positive_regulation Cause:T2 Theme:E21
E21	Gene_expression Theme:T5
E22	Positive_regulation Theme:E23
E23	Gene_expression Theme:T5
M1	Speculation E5
M2	Speculation E6
