T1	Protein	c-fos
T2	Protein	H2 receptor
T4	Protein	c-myc
T6	Protein	H2 receptors
E1	Regulation Theme:T2
E2	Regulation Theme:E3
E3	Gene_expression Theme:T1
E4	Regulation Theme:E6
E5	Regulation Theme:E7
E6	Transcription Theme:T4
E7	Transcription Theme:T1
E8	Positive_regulation Cause:E9 Theme:E10
E9	Positive_regulation Theme:T6
E10	Gene_expression Theme:T1
E11	Positive_regulation Theme:T1
E12	Positive_regulation Theme:T1
E13	Regulation Theme:E14
E14	Positive_regulation Theme:T1
E15	Positive_regulation Cause:T6 Theme:T1
E16	Negative_regulation Theme:E17
E17	Positive_regulation Theme:T1
E18	Regulation Theme:E17
E19	Regulation Theme:E20
E20	Gene_expression Theme:T4
E21	Negative_regulation Theme:T4
E22	Negative_regulation Theme:T2
E23	Positive_regulation Theme:E24
E24	Gene_expression Theme:T1
E25	Negative_regulation Theme:T6
M1	Speculation E4
M2	Speculation E5
M3	Negation E18
M4	Negation E19
