T1	Protein	Egr-1
T2	Protein	interleukin-2 receptor beta-chain
T3	Protein	interleukin-2 IL-2 receptor beta-chain
T4	Protein	IL-2Rbeta
T5	Protein	IL-2
T6	Protein	IL-15
T9	Protein	Sp1
T10	Protein	Sp3
*	Equiv T3 T4
T28	Entity	promoter
E1	Regulation Theme:T2
E2	Gene_expression Theme:T3
E3	Positive_regulation Theme:E2
E4	Binding Site:T28 Theme:T3
E5	Binding Theme:T10
E6	Binding Theme:T9
E7	Binding Theme:T1
E8	Binding Theme:T1
E9	Positive_regulation Site:T28 Theme:T3
E10	Gene_expression Theme:T1
E11	Positive_regulation Theme:E10
E12	Binding Theme:T9 Theme2:T1
E13	Gene_expression Theme:T1
E14	Positive_regulation Cause:T9 Theme:T3
E15	Positive_regulation Cause:T1 Theme:T3
