T1	Protein	vascular cell adhesion molecule-1
T2	Protein	VCAM-1
T3	Protein	E-selectin
T4	Protein	tumor necrosis factor-alpha
T5	Protein	TNF
T10	Protein	intercellular adhesion molecule-1
T11	Protein	ICAM-1
*	Equiv T1 T2
*	Equiv T4 T5
*	Equiv T10 T11
T24	Entity	surface
E1	Positive_regulation Cause:T4 Theme:T3
E2	Positive_regulation Cause:T4 Theme:T1
E3	Positive_regulation Theme:E2
E4	Positive_regulation Theme:E1
E5	Positive_regulation Cause:T4 Theme:E8
E6	Positive_regulation Cause:T4 Theme:E7
E7	Localization AtLoc:T24 Theme:T3
E8	Localization AtLoc:T24 Theme:T1
E9	Negative_regulation Theme:E6
E10	Negative_regulation Theme:E5
E11	Positive_regulation Theme:T10
E12	Regulation Theme:E11
E13	Negative_regulation Theme:E14
E14	Transcription Theme:T1
E15	Negative_regulation Theme:E16
E16	Positive_regulation Cause:T4 Theme:T1
E17	Negative_regulation Theme:E19
E18	Negative_regulation Theme:E20
E19	Positive_regulation Theme:T1
E20	Positive_regulation Theme:T3
E21	Regulation Theme:E17
E22	Regulation Theme:E18
E23	Negative_regulation Theme:E25
E24	Negative_regulation Theme:E26
E25	Positive_regulation Theme:T1
E26	Positive_regulation Theme:T3
M1	Negation E12
M2	Speculation E13
M3	Negation E21
M4	Negation E22
