T1	Protein	CD28
T2	Protein	acidic sphingomyelinase
T9	Protein	B7
T10	Protein	IL-2
E1	Positive_regulation Theme:T1
E2	Binding Theme:T1
E3	Positive_regulation Theme:T1
E4	Positive_regulation Theme:T1
E5	Gene_expression Theme:T9
E6	Positive_regulation Theme:E5
E7	Positive_regulation Cause:E4 Theme:E8
E8	Gene_expression Theme:T10
E9	Binding Theme:T1
E10	Positive_regulation Theme:E11
E11	Gene_expression Theme:T10
E12	Negative_regulation Theme:T2
M1	Negation E7
