T1	Protein	IL-2
T3	Protein	NFAT-1
T7	Protein	lac-Z
T9	Protein	beta-galactosidase
T23	Entity	promoter
E1	Negative_regulation Theme:T1
E2	Binding Theme:T3 Site2:T23 Theme2:T1
E3	Positive_regulation Cause:E2 Theme:E4
E4	Transcription Theme:T1
E5	Positive_regulation Theme:E6
E6	Negative_regulation Theme:T9
E7	Positive_regulation Cause:T3 Theme:T9
E8	Negative_regulation Theme:T9
E9	Negative_regulation Theme:E10
E10	Transcription Theme:T9
E11	Gene_expression Theme:T3
E12	Positive_regulation Theme:E11
E13	Negative_regulation Theme:E16
E14	Negative_regulation Theme:E15
E15	Transcription Theme:T1
E16	Gene_expression Theme:T1
E17	Negative_regulation Theme:E18
E18	Gene_expression Theme:T1
E19	Positive_regulation Theme:E18
E20	Positive_regulation Theme:E21
E21	Gene_expression Theme:T1
E22	Regulation Theme:E23
E23	Binding Theme:T3
M1	Speculation E5
