T1	Protein	CD4
T2	Protein	interleukin 2
T3	Protein	IL-2
T4	Protein	IL-4
T7	Protein	gamma interferon
*	Equiv T2 T3
E1	Regulation Theme:E4
E2	Regulation Theme:E3
E3	Regulation Theme:E6
E4	Regulation Theme:E5
E5	Gene_expression Theme:T2
E6	Gene_expression Theme:T4
E7	Gene_expression Theme:T4
E8	Gene_expression Theme:T7
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T2
E11	Gene_expression Theme:T2
E12	Gene_expression Theme:T4
E13	Positive_regulation Theme:E12
E14	Negative_regulation Theme:E16
E15	Gene_expression Theme:T4
E16	Regulation Theme:E15
E17	Negative_regulation Cause:E14 Theme:E18
E18	Positive_regulation Theme:E19
E19	Transcription Theme:T4
M1	Negation E11
M2	Speculation E14
M3	Speculation E16
M4	Speculation E17
