T1	Protein	IL-4
T3	Protein	IL-2
T4	Protein	CD4
T10	Protein	NFAT1
T33	Entity	P0
T34	Entity	P1 NFAT-binding elements
T35	Entity	promoter
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E6
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T1
E6	Gene_expression Theme:T3
E7	Gene_expression Theme:T3
E8	Positive_regulation Theme:E14
E9	Positive_regulation Theme:E13
E10	Positive_regulation Site:T35 Theme:T1
E11	Regulation Cause:E10 Theme:E13
E12	Regulation Cause:E10 Theme:E14
E13	Binding Site:T34 Theme:T1
E14	Binding Site:T33 Theme:T1
E15	Positive_regulation CSite:T34 Cause:T1 Site:T35 Theme:T1
E16	Positive_regulation CSite:T33 Cause:T1 Site:T35 Theme:T1
E17	Gene_expression Theme:T10
E18	Positive_regulation Theme:E17
E19	Gene_expression Theme:T10
E20	Positive_regulation Cause:E19 Site:T35 Theme:T1
E21	Negative_regulation Cause:T10 Theme:E22
E22	Gene_expression Theme:T1
E23	Negative_regulation Site:T35 Theme:T1
E24	Regulation Theme:E25
E25	Positive_regulation Theme:E26
E26	Gene_expression Theme:T1
E27	Regulation Cause:T10 Theme:E28
E28	Positive_regulation Theme:E29
E29	Gene_expression Theme:T1
M1	Negation E3
M2	Speculation E21
