T1	Protein	tumor necrosis factor
T3	Protein	Tumor necrosis factor alpha
T4	Protein	TNF-alpha
T9	Protein	chloramphenicol acetyltransferase
T10	Protein	beta interferon
*	Equiv T3 T4
T26	Entity	promoter
E1	Transcription Theme:T3
E2	Transcription Theme:T3
E3	Transcription Theme:T3
E4	Positive_regulation Theme:E5
E5	Positive_regulation Theme:T3
E6	Gene_expression Theme:T3
E7	Positive_regulation Theme:E6
E8	Positive_regulation Site:T26 Theme:T10
E9	Positive_regulation Cause:T3 Site:T26 Theme:T10
M1	Speculation E1
M2	Negation E2
