T1	Protein	IL-4
T2	Protein	IL-13
T7	Protein	p24 Ag
T13	Protein	CD11b
T14	Protein	CD13
T15	Protein	CD26
T16	Protein	CD14
T17	Protein	CD68
E1	Regulation Cause:T2 Theme:T15
E2	Regulation Cause:T1 Theme:T15
E3	Regulation Cause:T2 Theme:T17
E4	Regulation Cause:T1 Theme:T16
E5	Regulation Cause:T1 Theme:T13
E6	Regulation Cause:T2 Theme:T16
E7	Regulation Cause:T2 Theme:T13
E8	Regulation Cause:T1 Theme:T17
E9	Regulation Cause:T2 Theme:T14
E10	Regulation Cause:T1 Theme:T14
E11	Positive_regulation Cause:T1 Theme:E13
E12	Negative_regulation Cause:T13 Theme:E14
E13	Gene_expression Theme:T13
E14	Gene_expression Theme:T15
E15	Negative_regulation Cause:T13 Theme:E16
E16	Negative_regulation Theme:T14
E17	Positive_regulation Cause:T2 Theme:T13
E18	Positive_regulation Cause:T2 Theme:T14
E19	Regulation Cause:T2 Theme:T15
M1	Speculation E1
M2	Speculation E2
M3	Speculation E3
M4	Speculation E4
M5	Speculation E5
M6	Speculation E6
M7	Speculation E7
M8	Speculation E8
M9	Speculation E9
M10	Speculation E10
M11	Negation E19
