T1	Protein	LMP-1
T2	Protein	I kappa B alpha
T5	Protein	bcl2
T13	Protein	p105
T15	Protein	MAD3
*	Equiv T2 T15
E1	Regulation Cause:T1 Theme:T15
E2	Gene_expression Theme:T1
E3	Positive_regulation Cause:T1 Theme:E4
E4	Gene_expression Theme:T5
E5	Positive_regulation Cause:T1 Theme:T5
E6	Gene_expression Theme:T1
E7	Gene_expression Theme:T1
E8	Phosphorylation Theme:T15
E9	Positive_regulation Theme:E12
E10	Positive_regulation Theme:E11
E11	Transcription Theme:T15
E12	Transcription Theme:T13
E13	Regulation Cause:T1 Theme:T15
