T1	Protein	thromboxane receptor
T2	Protein	thromboxane receptors
T10	Protein	chloramphenicol acetyltransferase
T11	Protein	CAT
T12	Protein	Thromboxane receptor
*	Equiv T10 T11
T25	Entity	5' flanking region
T26	Entity	promoter
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:T2
E4	Regulation Theme:T2
E5	Transcription Theme:T1
E6	Positive_regulation Site:T25 Theme:T1
E7	Gene_expression Theme:T10
E8	Positive_regulation Site:T26 Theme:T12
E9	Gene_expression Theme:T1
E10	Regulation Theme:E9
E11	Positive_regulation Cause:E13 Theme:E12
E12	Positive_regulation Theme:T2
E13	Positive_regulation Theme:E14
E14	Transcription Theme:T1
M1	Speculation E4
M2	Speculation E6
