T1	Protein	pp52
T3	Protein	LSP-1
T4	Protein	WP-34
T5	Protein	pp52 leukocyte protein
T8	Protein	PU-1
T9	Protein	Ig/EBP-1
T10	Protein	nuclear factor-IL-6beta
*	Equiv T1 T3 T4
T16	Entity	promoter
T17	Entity	initiator
T19	Entity	5' terminus
T20	Entity	C/EBP motif
E1	Gene_expression Theme:T1
E2	Regulation CSite:T17 Cause:T1 Site:T19 Theme:T1
E3	Binding Site:T20 Theme:T1
E4	Binding Site:T17 Theme:T1
E5	Binding Theme:T8
E6	Binding Theme:T9
E7	Binding Theme:T10
E8	Binding Theme:T10
E9	Binding Theme:T9
E10	Positive_regulation Cause:T9 Site:T16 Theme:T1
E11	Regulation Site:T16 Theme:T1
E12	Regulation Site:T16 Theme:T1
M1	Speculation E10
