T1	Protein	vascular cell adhesion molecule (VCAM)-1
T2	Protein	VCAM-1
T7	Protein	intercellular adhesion molecule-1
T8	Protein	E-selectin
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T2
E5	Negative_regulation Theme:E6
E6	Positive_regulation Theme:T2
E7	Positive_regulation Theme:T2
E8	Negative_regulation Theme:E7
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T2
E11	Positive_regulation Theme:E13
E12	Positive_regulation Theme:E14
E13	Gene_expression Theme:T7
E14	Gene_expression Theme:T8
E15	Positive_regulation Theme:T7
E16	Positive_regulation Theme:T2
M1	Negation E9
