T1	Protein	vascular cell adhesion molecule-1
T2	Protein	Tax
T3	Protein	vascular cell adhesion molecule 1
T4	Protein	VCAM-1
T5	Protein	CD106
T8	Protein	tax
T13	Protein	chloramphenicol acetyltransferase
T35	Entity	promoter
T37	Entity	NF-kappaB sites
E1	Positive_regulation Theme:T1
E2	Gene_expression Theme:T2
E3	Gene_expression Theme:T4
E4	Positive_regulation Theme:E3
E5	Gene_expression Theme:T4
E6	Gene_expression Theme:T4
E7	Regulation Cause:T2 Theme:E8
E8	Positive_regulation Theme:T4
E9	Gene_expression Theme:T4
E10	Gene_expression Theme:T8
E11	Regulation Cause:T2 Theme:E12
E12	Transcription Theme:T4
E13	Positive_regulation Cause:E14 Site:T35 Theme:T4
E14	Binding Theme:T2 Site2:T37 Theme2:T4
E15	Positive_regulation CSite:T37 Cause:T4 Theme:E16
E16	Positive_regulation Cause:T2 Theme:E17
E17	Gene_expression Theme:T4
E18	Positive_regulation Theme:T4
E19	Gene_expression Theme:T2
E20	Regulation Theme:E18
E21	Positive_regulation Cause:T2 Theme:E22
E22	Gene_expression Theme:T4
M1	Negation E6
M2	Speculation E7
