T1	Protein	vitamin D receptor
T3	Protein	VDR
T7	Protein	c-myc
T8	Protein	DNA-PK(CS)
T9	Protein	17beta-hydroxysteroid dehydrogenase type IV
T10	Protein	17beta-HSD IV
*	Equiv T9 T10
*	Equiv T1 T3
E1	Negative_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Gene_expression Theme:T1
E4	Positive_regulation Theme:E3
E5	Negative_regulation Theme:E3
E6	Gene_expression Theme:T1
E7	Negative_regulation Theme:T1
E8	Positive_regulation Theme:E9
E9	Transcription Theme:T7
E10	Transcription Theme:T8
E11	Transcription Theme:T9
E12	Negative_regulation Cause:E14 Theme:E11
E13	Negative_regulation Cause:E14 Theme:E10
E14	Negative_regulation Theme:T1
E15	Negative_regulation Theme:E16
E16	Transcription Theme:T9
E17	Regulation Theme:T8
E18	Regulation Theme:T9
E19	Gene_expression Theme:T9
E20	Gene_expression Theme:T8
M1	Negation E17
M2	Negation E18
