T1	Protein	vitamin D3 receptors
T2	Protein	VDR
T4	Protein	interleukin-4
T6	Protein	CD23
T7	Protein	24-hydroxylase
*	Equiv T1 T2
E1	Positive_regulation Theme:T1
E2	Transcription Theme:T1
E3	Positive_regulation Theme:T1
E4	Regulation Theme:T6
E5	Regulation Theme:T7
E6	Negative_regulation Theme:E7
E7	Gene_expression Theme:T6
E8	Regulation Theme:E9
E9	Gene_expression Theme:T6
E10	Positive_regulation Theme:E11
E11	Transcription Theme:T7
E12	Positive_regulation Theme:T7
E13	Transcription Theme:T1
E14	Gene_expression Theme:T1
M1	Negation E2
M2	Speculation E4
M3	Speculation E5
M4	Negation E8
M5	Negation E12
