T1	Protein	IL-2 receptor alpha-chain
T2	Protein	IL-2
T3	Protein	IL-2R alpha
T12	Entity	protein kinase C-independent mechanism
E1	Positive_regulation Cause:E2 Theme:T1
E2	Positive_regulation Site:T12 Theme:T1
E3	Positive_regulation Theme:T2
E4	Positive_regulation Theme:T3
E5	Positive_regulation Theme:T3
E6	Positive_regulation Theme:T3
E7	Regulation Theme:E8
E8	Gene_expression Theme:T3
E9	Positive_regulation Theme:T3
E10	Positive_regulation Theme:T3
E11	Negative_regulation Theme:E10
E12	Positive_regulation Theme:T3
E13	Negative_regulation Theme:E12
E14	Positive_regulation Theme:T3
M1	Negation E3
M2	Negation E13
