T1	Protein	CTCF
T2	Protein	c-myc
E1	Gene_expression Theme:T1
E2	Phosphorylation Theme:T1
E3	Regulation Cause:T1 Theme:T2
E4	Negative_regulation Cause:T1 Theme:T2
E5	Regulation Theme:T1
E6	Gene_expression Theme:T1
E7	Phosphorylation Theme:T1
E8	Negative_regulation Theme:T1
E9	Negative_regulation Theme:T1
E10	Negative_regulation Theme:T2
E11	Phosphorylation Theme:T1
E12	Positive_regulation Theme:E11
E13	Gene_expression Theme:T1
E14	Regulation Theme:E13
E15	Regulation Theme:T1
M1	Speculation E6
M2	Speculation E7
