T1	Protein	IL-4
T2	Protein	granulocyte-macrophage CSF
T3	Protein	CD86
T4	Protein	B7-2
T5	Protein	CD40
T7	Protein	mannose receptor
*	Equiv T3 T4
E1	Negative_regulation Theme:E5
E2	Negative_regulation Theme:E6
E3	Negative_regulation Theme:E7
E4	Negative_regulation Theme:E8
E5	Gene_expression Theme:T3
E6	Gene_expression Theme:T5
E7	Positive_regulation Theme:E5
E8	Positive_regulation Theme:E6
E9	Binding Theme:T5
