T1	Protein	c-fos
T2	Protein	c-jun
T3	Protein	phytohemagglutinin
T5	Protein	p62c-fos
T7	Protein	p39c-jun
T8	Protein	phyto- hemagglutinin
T9	Protein	PHA
*	Equiv T8 T9
*	Equiv T1 T5
*	Equiv T2 T7
T31	Entity	nuclear
T33	Entity	Nuclei
E1	Gene_expression Theme:T7
E2	Gene_expression Theme:T5
E3	Transcription Theme:T5
E4	Transcription Theme:T7
E5	Gene_expression Theme:T7
E6	Gene_expression Theme:T5
E7	Gene_expression Theme:T5
E8	Gene_expression Theme:T7
E9	Localization AtLoc:T31 Theme:T5
E10	Localization AtLoc:T31 Theme:T7
E11	Positive_regulation Theme:T7
E12	Positive_regulation Theme:T5
E13	Localization AtLoc:T33 Theme:T5
E14	Localization AtLoc:T33 Theme:T7
E15	Positive_regulation Theme:E16
E16	Gene_expression Theme:T7
E17	Gene_expression Theme:T7
E18	Gene_expression Theme:T5
E19	Gene_expression Theme:T5
E20	Gene_expression Theme:T7
M1	Speculation E3
M2	Speculation E4
M3	Speculation E5
M4	Speculation E6
M5	Speculation E7
M6	Speculation E8
M7	Negation E11
M8	Negation E12
M9	Negation E19
