T1	Protein	IL-4
T8	Entity	promoter
E1	Positive_regulation CSite:T8 Cause:T1 Theme:E2
E2	Positive_regulation Theme:E3
E3	Gene_expression Theme:T1
E4	Positive_regulation Theme:E6
E5	Gene_expression Theme:T1
E6	Positive_regulation Theme:E5
E7	Transcription Theme:T1
E8	Gene_expression Theme:T1
E9	Positive_regulation Theme:E10
E10	Transcription Theme:T1
E11	Positive_regulation Theme:E12
E12	Positive_regulation Theme:E13
E13	Gene_expression Theme:T1
M1	Speculation E4
