T1	Protein	colony-stimulating factor 1 (macrophage colony-stimulating factor) receptor
T2	Protein	AML1
T3	Protein	macrophage colony-stimulating factor
T4	Protein	colony-stimulating factor 1
T5	Protein	CSF-1
T6	Protein	CSF-1 receptor
T7	Protein	PU.1
T13	Entity	promoter
E1	Regulation Site:T13 Theme:T1
E2	Binding Theme:T2
E3	Gene_expression Theme:T6
E4	Regulation Theme:E3
E5	Binding Theme:T2
E6	Regulation Cause:T7 Theme:E7
E7	Transcription Theme:T6
M1	Speculation E1
M2	Speculation E2
