T1	Protein	IkappaBalpha
T2	Protein	IkappaBalpha kinase
T3	Protein	p90(rsk)
T7	Protein	IKKalpha
T8	Protein	-beta
T9	Protein	IKKbeta
E1	Phosphorylation Theme:T1
E2	Protein_catabolism Theme:T1
E3	Positive_regulation Theme:T3
E4	Regulation Cause:T3 Theme:E6
E5	Regulation Theme:E6
E6	Phosphorylation Theme:T1
E7	Positive_regulation Theme:E6
E8	Negative_regulation Theme:E9
E9	Phosphorylation Theme:T1
E10	Regulation Theme:T9
M1	Negation E3
M2	Negation E4
