T1	Protein	GATA1
T2	Protein	interleukin-3
T3	Protein	IL-3
T4	Protein	granulocyte-macrophage colony-stimulating factor
T5	Protein	GM-CSF
T6	Protein	erythropoietin
T7	Protein	Ep
T8	Protein	c-kit ligand
*	Equiv T2 T3
*	Equiv T4 T5
*	Equiv T6 T7
E1	Gene_expression Theme:T1
E2	Gene_expression Theme:T1
E3	Negative_regulation Theme:E4
E4	Positive_regulation Theme:T1
E5	Negative_regulation Theme:E6
E6	Positive_regulation Theme:T1
