T1	Protein	MAD3
T2	Protein	I kappa B alpha
*	Equiv T1 T1 T2 T2
E1	Regulation Theme:E2
E2	Protein_catabolism Theme:T1
E3	Positive_regulation Theme:E2
E4	Protein_catabolism Theme:T1
E5	Positive_regulation Theme:E4
E6	Gene_expression Theme:T1
E7	Protein_catabolism Theme:T1
E8	Positive_regulation Theme:E7
E9	Positive_regulation Theme:T1
E10	Phosphorylation Theme:T1
E11	Positive_regulation Theme:E13
E12	Positive_regulation Theme:E14
E13	Phosphorylation Theme:T1
E14	Protein_catabolism Theme:T1
E15	Positive_regulation Theme:E16
E16	Phosphorylation Theme:T1
E17	Negative_regulation Theme:E19
E18	Positive_regulation Theme:E19
E19	Protein_catabolism Theme:T1
E20	Negative_regulation Theme:E23
E21	Negative_regulation Theme:E22
E22	Positive_regulation Theme:E23
E23	Phosphorylation Theme:T1
M1	Speculation E6
