T1	Protein	Interleukin 4
T2	Protein	interferon-gamma
T3	Protein	Janus kinase 3
T4	Protein	interleukin-4
T5	Protein	IL-4
T6	Protein	IFN-gamma
T11	Protein	IL-4 Stat
T12	Protein	Stat6
T16	Protein	JAK3
*	Equiv T11 T12
*	Equiv T3 T16
E1	Positive_regulation Cause:T5 Theme:T3
E2	Positive_regulation Theme:E5
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T5
E5	Gene_expression Theme:T3
E6	Binding Theme:T5
E7	Positive_regulation Cause:T3 Theme:T5
E8	Positive_regulation Theme:E7
