T1	Protein	p40
T2	Protein	CD40
T4	Protein	CD40 ligand
T5	Protein	CD40L
T16	Protein	chloramphenicol acetyltransferase
T17	Protein	CAT
*	Equiv T16 T17
*	Equiv T4 T5
E1	Positive_regulation Theme:E2
E2	Transcription Theme:T1
E3	Binding Theme:T2
E4	Binding Theme:T2 Theme2:T5
E5	Transcription Theme:T1
E6	Positive_regulation Theme:E5
E7	Positive_regulation Cause:E9 Theme:T2
E8	Positive_regulation Cause:E9 Theme:T1
E9	Binding Theme:T2
E10	Localization Theme:T1
E11	Positive_regulation Theme:E12
E12	Transcription Theme:T1
E13	Binding Theme:T2
E14	Positive_regulation Theme:T16
E15	Positive_regulation Theme:E16
E16	Positive_regulation Theme:T1
E17	Binding Theme:T2
M1	Speculation E5
M2	Speculation E6
M3	Negation E14
M4	Speculation E15
