T1	Protein	oriP
T2	Protein	Cp
T3	Protein	Wp
T10	Protein	EBNA2
T26	Protein	EBNA 1
T27	Protein	EBNA 2
E1	Positive_regulation Theme:T3
E2	Negative_regulation Theme:E1
E3	Positive_regulation Theme:T2
E4	Negative_regulation Theme:T2
E5	Negative_regulation Theme:T2
E6	Positive_regulation Theme:T2
E7	Positive_regulation Theme:T2
E8	Negative_regulation Theme:T2
E9	Negative_regulation Theme:T2
E10	Positive_regulation Cause:E9 Theme:T3
E11	Negative_regulation Theme:T3
E12	Regulation Theme:T2
E13	Regulation Cause:T1 Theme:T2
M1	Negation E8
