T1	Protein	PEBP2 alpha A
T2	Protein	PEBP2 alpha B
T4	Protein	AML1
T6	Protein	AML1/PEBP2 alpha B
T7	Protein	CD4
E1	Gene_expression Theme:T2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E2
E4	Positive_regulation Theme:E1
E5	Transcription Theme:T6
E6	Transcription Theme:T1
E7	Gene_expression Theme:T6
E8	Gene_expression Theme:T1
E9	Positive_regulation Theme:E7
E10	Positive_regulation Theme:E8
E11	Transcription Theme:T6
E12	Transcription Theme:T1
E13	Gene_expression Theme:T1
E14	Gene_expression Theme:T6
E15	Transcription Theme:T6
E16	Gene_expression Theme:T6
