T1	Protein	Mn SOD
T2	Protein	Mn superoxide dismutase
T3	Protein	Cu,Zn SOD
T4	Protein	catalase
T7	Protein	tumor necrosis factor-alpha
T8	Protein	macrophage inflammatory protein-1alpha
E1	Positive_regulation Theme:T1
E2	Positive_regulation Theme:T2
E3	Regulation Theme:T3
E4	Regulation Theme:T4
E5	Positive_regulation Theme:T1
E6	Positive_regulation Theme:E7
E7	Transcription Theme:T1
E8	Positive_regulation Theme:E11
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T8
E11	Gene_expression Theme:T7
E12	Positive_regulation Theme:E13
E13	Positive_regulation Theme:T1
E14	Positive_regulation Theme:T1
E15	Regulation Theme:E14
E16	Positive_regulation Theme:E17
E17	Gene_expression Theme:T7
E18	Positive_regulation Theme:E16
M1	Negation E3
M2	Negation E4
M3	Negation E8
M4	Negation E9
M5	Negation E12
M6	Negation E16
