T1	Protein	tumour necrosis factor alpha
T3	Protein	TNF-alpha
T6	Protein	TNF-alpha receptor type II
*	Equiv T1 T3
E1	Negative_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Negative_regulation Theme:T1
E4	Negative_regulation Theme:T1
E5	Positive_regulation Cause:E7 Theme:E6
E6	Negative_regulation Theme:T6
E7	Binding Theme:T6
E8	Positive_regulation Theme:E9
E9	Transcription Theme:T1
E10	Negative_regulation Theme:T1
