T1	Protein	IkB alpha
T9	Protein	TNF-alpha
E1	Regulation Theme:E2
E2	Phosphorylation Theme:T1
E3	Positive_regulation Theme:E4
E4	Positive_regulation Theme:E5
E5	Protein_catabolism Theme:T1
E6	Regulation Theme:E7
E7	Phosphorylation Theme:T1
E8	Positive_regulation Theme:E11
E9	Positive_regulation Theme:E10
E10	Phosphorylation Theme:T1
E11	Protein_catabolism Theme:T1
E12	Positive_regulation Theme:E13
E13	Phosphorylation Theme:T1
E14	Negative_regulation Theme:E15
E15	Protein_catabolism Theme:T1
E16	Positive_regulation Theme:E19
E17	Positive_regulation Theme:E18
E18	Phosphorylation Theme:T1
E19	Protein_catabolism Theme:T1
E20	Negative_regulation Theme:E30
E21	Negative_regulation Theme:E31
E22	Negative_regulation Theme:E24
E23	Negative_regulation Theme:E25
E24	Positive_regulation Theme:E27
E25	Positive_regulation Theme:E26
E26	Phosphorylation Theme:T1
E27	Protein_catabolism Theme:T1
E28	Phosphorylation Theme:T1
E29	Protein_catabolism Theme:T1
E30	Positive_regulation Cause:T9 Theme:E28
E31	Positive_regulation Cause:T9 Theme:E29
E32	Positive_regulation Cause:T9 Theme:E34
E33	Positive_regulation Cause:T9 Theme:E35
E34	Phosphorylation Theme:T1
E35	Protein_catabolism Theme:T1
E36	Positive_regulation Theme:E38
E37	Positive_regulation Theme:E39
E38	Phosphorylation Theme:T1
E39	Protein_catabolism Theme:T1
M1	Negation E16
M2	Negation E17
M3	Negation E20
M4	Negation E21
M5	Negation E32
