T1	Protein	tumor necrosis factor alpha
T3	Protein	TNF-alpha
*	Equiv T1 T3
T10	Entity	promoter
T18	Entity	kappa 1
T19	Entity	kappa 2
T20	Entity	kappa 3
E1	Regulation Theme:T1
E2	Positive_regulation CSite:T10 Cause:T1 Theme:E3
E3	Positive_regulation Theme:T1
E4	Positive_regulation Theme:E5
E5	Positive_regulation Theme:T1
E6	Positive_regulation Theme:E3
E7	Positive_regulation Theme:E8
E8	Positive_regulation Theme:T1
E9	Binding Site:T20 Theme:T1
E10	Binding Site:T18 Theme:T1
E11	Binding Site:T19 Theme:T1
E12	Positive_regulation Theme:T1
E13	Positive_regulation Theme:T1
E14	Positive_regulation Theme:T1
E15	Positive_regulation Theme:T1
E16	Positive_regulation Theme:E15
E17	Positive_regulation Theme:E14
M1	Speculation E4
M2	Negation E16
M3	Negation E17
