T1	Protein	Rel-A
T2	Protein	c-Rel
T3	Protein	p50
T4	Protein	p65
T15	Protein	CD4
T18	Entity	Nuclear
E1	Localization AtLoc:T18 Theme:T2
E2	Localization AtLoc:T18 Theme:T1
E3	Positive_regulation Theme:T2
E4	Positive_regulation Theme:T3
E5	Gene_expression Theme:T4
E6	Gene_expression Theme:T3
E7	Gene_expression Theme:T4
E8	Gene_expression Theme:T4
E9	Gene_expression Theme:T2
E10	Gene_expression Theme:T3
