T1	Protein	CD44
T2	Protein	VCAM-1
T11	Protein	IL-1beta
T12	Protein	TNF-alpha
T15	Protein	AP-1
E1	Positive_regulation Theme:T2
E2	Binding Theme:T1
E3	Binding Theme:T1
E4	Positive_regulation Cause:E3 Theme:E5
E5	Gene_expression Theme:T2
E6	Gene_expression Theme:T1
E7	Binding Theme:T1
E8	Positive_regulation Cause:E7 Theme:E14
E9	Positive_regulation Cause:E7 Theme:E16
E10	Positive_regulation Cause:E7 Theme:E12
E11	Positive_regulation Cause:E7 Theme:E15
E12	Gene_expression Theme:T2
E13	Gene_expression Theme:T11
E14	Transcription Theme:T2
E15	Transcription Theme:T11
E16	Transcription Theme:T12
E17	Positive_regulation Theme:T2
E18	Positive_regulation Cause:T1 Theme:T15
E19	Binding Theme:T1
E20	Positive_regulation Theme:E21
E21	Gene_expression Theme:T2
