T1	Protein	GATA-1
T2	Protein	erythropoietin
T3	Protein	bcl-xL
T9	Protein	bcl-2
T10	Protein	mcl-1
E1	Regulation Cause:T1 Theme:E3
E2	Regulation Cause:T2 Theme:E3
E3	Gene_expression Theme:T3
E4	Positive_regulation Cause:T1 Theme:E9
E5	Positive_regulation Cause:T1 Theme:E8
E6	Positive_regulation Cause:T1 Theme:E7
E7	Gene_expression Theme:T9
E8	Gene_expression Theme:T3
E9	Gene_expression Theme:T10
E10	Positive_regulation Cause:T2 Theme:E12
E11	Positive_regulation Cause:T1 Theme:E12
E12	Gene_expression Theme:T3
E13	Regulation Cause:T2 Theme:T3
E14	Regulation Cause:T1 Theme:T3
M1	Negation E4
M2	Negation E6
