T1	Protein	beta-globin
T5	Protein	GATA-1
T6	Protein	Sp-1
T7	Protein	DNase 1
T16	Entity	promoters
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Transcription Theme:T1
E4	Positive_regulation Site:T16 Theme:T1
E5	Positive_regulation Theme:E8
E6	Positive_regulation Theme:E7
E7	Transcription Theme:T1
E8	Positive_regulation Theme:T1
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T1
M1	Speculation E3
