T1	Protein	Retinoblastoma
T2	Protein	Oct-1
T3	Protein	interleukin-8
T4	Protein	retinoblastoma
T5	Protein	IFN-gamma
T6	Protein	Rb
T15	Protein	interleukin 8
T31	Entity	promoter
E1	Gene_expression Theme:T1
E2	Negative_regulation Cause:E1 Theme:E3
E3	Binding Theme:T2
E4	Positive_regulation Cause:E1 Theme:E5
E5	Gene_expression Theme:T3
E6	Negative_regulation Theme:T4
E7	Gene_expression Theme:T6
E8	Negative_regulation Theme:T6
E9	Gene_expression Theme:T6
E10	Positive_regulation Cause:E9 Theme:E11
E11	Phosphorylation Theme:T2
E12	Negative_regulation Cause:T2 Site:T31 Theme:T15
E13	Negative_regulation Theme:E14
E14	Binding Theme:T2
E15	Gene_expression Theme:T15
E16	Positive_regulation Theme:E15
