T1	Protein	GrpL
T2	Protein	Grb2
T3	Protein	SLP-76
T4	Protein	SH2 domain-containing protein 76
T6	Protein	Vav
T8	Protein	Grb2-related protein of the lymphoid system
T14	Protein	Sos1
T15	Protein	Sos2
T20	Protein	LAT
T21	Protein	pp36/38
*	Equiv T1 T8
*	Equiv T20 T21
*	Equiv T3 T4
T36	Entity	tyrosine
E1	Binding Theme:T1 Theme2:T3
E2	Binding Theme:T3 Theme2:T6
E3	Gene_expression Theme:T3
E4	Gene_expression Theme:T1
E5	Binding Theme:T1 Theme2:T14
E6	Binding Theme:T1 Theme2:T15
E7	Binding Theme:T1 Theme2:T3
E8	Binding Theme:T2 Theme2:T14
E9	Binding Theme:T2 Theme2:T3
E10	Binding Theme:T2 Theme2:T15
E11	Phosphorylation Site:T36 Theme:T21
E12	Binding Theme:T21 Theme2:T2
E13	Binding Theme:T21 Theme2:T1
M1	Negation E5
M2	Negation E6
M3	Negation E9
M4	Negation E13
