T1	Protein	STAT6
T2	Protein	interleukin 4
T3	Protein	SOCS-1
T4	Protein	IL-4
T7	Protein	signal transducer and activator of transcription-6
T14	Protein	IFN-beta
T15	Protein	IFN-gamma
T16	Protein	IL-1
T17	Protein	IL-2
T18	Protein	IL-6
T19	Protein	transforming growth factor beta
*	Equiv T1 T7
T38	Entity	tyrosine
T41	Entity	nuclear
E1	Negative_regulation Cause:E3 Theme:E2
E2	Positive_regulation Cause:T2 Theme:T7
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T3
E5	Positive_regulation Cause:T4 Theme:E9
E6	Positive_regulation Cause:T4 Theme:E10
E7	Positive_regulation Cause:T4 Theme:E8
E8	Phosphorylation Site:T38 Theme:T7
E9	Binding Theme:T7
E10	Localization Theme:T7 ToLoc:T41
E11	Positive_regulation Theme:T7
E12	Regulation Theme:E13
E13	Positive_regulation Cause:T4 Theme:T7
E14	Negative_regulation Cause:T14 Theme:E20
E15	Negative_regulation Cause:T16 Theme:E20
E16	Negative_regulation Cause:T15 Theme:E20
E17	Negative_regulation Cause:T18 Theme:E20
E18	Negative_regulation Cause:T19 Theme:E20
E19	Negative_regulation Cause:T17 Theme:E20
E20	Positive_regulation Cause:T4 Theme:T7
E21	Negative_regulation Theme:E23
E22	Negative_regulation Theme:E24
E23	Phosphorylation Site:T38 Theme:T7
E24	Localization Theme:T7 ToLoc:T41
E25	Positive_regulation Theme:T3
E26	Gene_expression Theme:T3
E27	Negative_regulation Cause:E29 Theme:E28
E28	Positive_regulation Cause:T4 Theme:T7
E29	Positive_regulation Theme:E30
E30	Gene_expression Theme:T3
M1	Speculation E12
M2	Negation E15
M3	Negation E17
M4	Negation E18
M5	Negation E19
