T1	Protein	IkappaBbeta
T2	Protein	tax
T3	Protein	IkappaBalpha
T6	Protein	Tax
E1	Negative_regulation Cause:T2 Theme:T1
E2	Binding Theme:T3
E3	Binding Theme:T1
E4	Phosphorylation Theme:T3
E5	Protein_catabolism Theme:T3
E6	Positive_regulation Theme:E5
E7	Gene_expression Theme:T6
E8	Positive_regulation Cause:T6 Theme:E9
E9	Protein_catabolism Theme:T3
E10	Regulation Cause:T6 Theme:T3
E11	Positive_regulation Cause:T6 Theme:E12
E12	Protein_catabolism Theme:T1
E13	Gene_expression Theme:T6
E14	Positive_regulation Theme:E13
E15	Negative_regulation Theme:E13
E16	Positive_regulation Cause:T6 Theme:E17
E17	Positive_regulation Theme:E18
E18	Transcription Theme:T3
E19	Gene_expression Theme:T1
E20	Negative_regulation Theme:E19
E21	Gene_expression Theme:T6
