T1	Protein	NF-M
T2	Protein	c-Myb
T4	Protein	C/EBP-beta
T5	Protein	NF-IL6
T7	Protein	CRP1
T8	Protein	C/EBP-epsilon
*	Equiv T1 T4 T5
*	Equiv T7 T8
E1	Gene_expression Theme:T1
E2	Positive_regulation Theme:E1
E3	Transcription Theme:T1
E4	Positive_regulation Theme:E3
E5	Binding Theme:T7
E6	Gene_expression Theme:T7
E7	Positive_regulation Theme:E6
E8	Negative_regulation Theme:T7
E9	Gene_expression Theme:T7
