T1	Protein	bcl-2
T24	Entity	promoter
T37	Entity	CRE site
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Transcription Theme:T1
E4	Gene_expression Theme:T1
E5	Positive_regulation Theme:E3
E6	Positive_regulation Cause:E7 Theme:E4
E7	Binding Theme:T1
E8	Regulation Theme:E9
E9	Regulation Theme:E10
E10	Gene_expression Theme:T1
E11	Negative_regulation Theme:E12
E12	Positive_regulation Site:T24 Theme:T1
E13	Regulation Theme:E14
E14	Gene_expression Theme:T1
E15	Positive_regulation Theme:E16
E16	Gene_expression Theme:T1
E17	Positive_regulation Theme:E16
E18	Gene_expression Theme:T1
E19	Positive_regulation Theme:E18
E20	Positive_regulation Theme:E18
E21	Positive_regulation Theme:E22
E22	Positive_regulation Theme:E23
E23	Gene_expression Theme:T1
E24	Positive_regulation Theme:E22
E25	Positive_regulation CSite:T37 Cause:T1 Theme:E26
E26	Positive_regulation Theme:E27
E27	Gene_expression Theme:T1
E28	Regulation Theme:E29
E29	Positive_regulation Theme:E30
E30	Gene_expression Theme:T1
E31	Regulation Theme:E28
M1	Speculation E25
M2	Speculation E26
M3	Speculation E27
M4	Speculation E28
M5	Speculation E31
