T1	Protein	MKK3
T2	Protein	MKK4
T3	Protein	MKK6
T5	Protein	p38alpha
T6	Protein	p38delta
T8	Protein	p38alpha MAPk
T9	Protein	tumor necrosis factor-alpha
T10	Protein	TNF-alpha
*	Equiv T9 T10
E1	Gene_expression Theme:T6
E2	Gene_expression Theme:T5
E3	Positive_regulation Theme:T5
E4	Negative_regulation Theme:T8
E5	Negative_regulation Cause:E4 Theme:E6
E6	Gene_expression Theme:T9
E7	Negative_regulation Theme:T8
E8	Negative_regulation Cause:E7 Theme:E9
E9	Gene_expression Theme:T9
E10	Positive_regulation Theme:E11
E11	Positive_regulation Theme:T1
E12	Positive_regulation Cause:E10 Theme:T8
E13	Positive_regulation Cause:E12 Theme:E14
E14	Gene_expression Theme:T9
E15	Regulation Cause:E12 Theme:E16
E16	Gene_expression Theme:T9
