T1	Protein	bcl-2
T2	Protein	LMP1
T6	Protein	Bcl-2
T11	Protein	ICAM-1
E1	Positive_regulation Cause:T2 Theme:T1
E2	Positive_regulation Cause:T2 Theme:T1
E3	Positive_regulation Cause:E4 Theme:T6
E4	Gene_expression Theme:T2
E5	Positive_regulation Cause:T2 Theme:T2
E6	Gene_expression Theme:T2
E7	Positive_regulation Theme:T11
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T2
E10	Positive_regulation Theme:T11
E11	Positive_regulation Theme:T6
E12	Gene_expression Theme:T2
E13	Gene_expression Theme:T2
E14	Gene_expression Theme:T6
E15	Gene_expression Theme:T11
E16	Positive_regulation Cause:E13 Theme:T11
E17	Positive_regulation Cause:E13 Theme:T6
E18	Positive_regulation Theme:T6
M1	Speculation E3
M2	Speculation E5
M3	Negation E17
