T1	Protein	BOB.1
T2	Protein	OBF.1
T5	Protein	Oct1
T6	Protein	Oct2
*	Equiv T1 T1 T2 T2
T21	Entity	Ser184
E1	Positive_regulation Theme:E3
E2	Positive_regulation Theme:E4
E3	Gene_expression Theme:T2
E4	Phosphorylation Theme:T2
E5	Gene_expression Theme:T2
E6	Binding Theme:T2 Theme2:T6
E7	Binding Theme:T2 Theme2:T5
E8	Gene_expression Theme:T2
E9	Positive_regulation Theme:E8
E10	Phosphorylation Site:T21 Theme:T2
E11	Positive_regulation Cause:E10 Theme:T2
E12	Positive_regulation Theme:E10
E13	Positive_regulation Theme:E12
E14	Regulation Theme:T2
