T1	Protein	small nuclear RNA
T3	Protein	snRNA
T4	Protein	PTF gamma
T5	Protein	delta subunits
T6	Protein	PTF beta
T12	Protein	TATA-binding protein
T13	Protein	TBP
T14	Protein	TFIIIB90
T16	Protein	PTF delta
*	Equiv T1 T3
*	Equiv T12 T13
E1	Transcription Theme:T3
E2	Positive_regulation Theme:E1
E3	Binding Theme:T3
E4	Transcription Theme:T3
E5	Positive_regulation Theme:E4
E6	Positive_regulation Theme:E7
E7	Transcription Theme:T3
E8	Gene_expression Theme:T6
E9	Binding Theme:T6
E10	Positive_regulation Cause:T6 Theme:E11
E11	Transcription Theme:T3
E12	Binding Theme:T13
E13	Binding Theme:T14
E14	Binding Theme:T4 Theme2:T13
E15	Binding Theme:T16 Theme2:T13
E16	Transcription Theme:T3
E17	Positive_regulation Theme:E18
E18	Transcription Theme:T3
E19	Positive_regulation Cause:E21 Theme:E17
E20	Positive_regulation Theme:E17
E21	Binding Theme:T13
