T1	Protein	Interleukin-2
T2	Protein	IL-2
T5	Protein	p56lck
T7	Protein	lck
*	Equiv T1 T2
T14	Entity	enhancer
E1	Regulation Theme:E2
E2	Transcription Theme:T1
E3	Binding Site:T14 Theme:T1
E4	Negative_regulation Theme:E5
E5	Transcription Theme:T1
E6	Regulation Cause:T5 Theme:E7
E7	Gene_expression Theme:T1
E8	Negative_regulation Theme:T7
E9	Negative_regulation Theme:E10
E10	Gene_expression Theme:T7
E11	Positive_regulation Theme:E12
E12	Gene_expression Theme:T1
M1	Negation E8
M2	Negation E9
