T1	Protein	tax
T2	Protein	c-sis
T3	Protein	platelet-derived growth factor-B
T4	Protein	Sp1
T5	Protein	NGFI-A
T6	Protein	Egr-1
T9	Protein	PDGF-B
T10	Protein	Tax
T16	Protein	Sp3
*	Equiv T5 T5 T6 T6
*	Equiv T2 T2 T3 T3 T9 T9
T44	Entity	promoter
E1	Positive_regulation Cause:E4 Site:T44 Theme:T3
E2	Positive_regulation Cause:E3 Site:T44 Theme:T3
E3	Binding Theme:T1 Theme2:T4
E4	Binding Theme:T1 Theme2:T5
E5	Positive_regulation Cause:T10 Theme:T3
E6	Binding Theme:T4
E7	Binding Theme:T16
E8	Binding Theme:T5
E9	Positive_regulation Cause:T10 Theme:T3
E10	Positive_regulation Cause:T10 Theme:E11
E11	Transcription Theme:T3
E12	Positive_regulation Cause:T10 Theme:E15
E13	Positive_regulation Cause:T10 Theme:E14
E14	Binding Theme:T5
E15	Binding Theme:T4
E16	Positive_regulation Site:T44 Theme:T3
E17	Binding Theme:T10 Theme2:T4
E18	Binding Theme:T10 Theme2:T5
E19	Binding Theme:T5
E20	Binding Theme:T5
M1	Negation E16
M2	Negation E19
