T1	Protein	RelA
T2	Protein	c-Rel
T3	Protein	I kappa B alpha
T4	Protein	IL-2
T5	Protein	IL-2R alpha
T6	Protein	IL-4
T7	Protein	IL-10
T8	Protein	IFN-gamma
E1	Negative_regulation Cause:E3 Theme:T1
E2	Negative_regulation Cause:E3 Theme:T2
E3	Gene_expression Theme:T3
E4	Gene_expression Theme:T3
E5	Gene_expression Theme:T5
E6	Gene_expression Theme:T4
E7	Negative_regulation Theme:E9
E8	Negative_regulation Theme:E10
E9	Gene_expression Theme:T4
E10	Gene_expression Theme:T5
E11	Gene_expression Theme:T7
E12	Gene_expression Theme:T6
E13	Gene_expression Theme:T8
E14	Negative_regulation Theme:E12
E15	Negative_regulation Theme:E11
M1	Speculation E5
M2	Speculation E6
