T1	Protein	GATA-3
T2	Protein	interleukin-5
T3	Protein	Interleukin-5
T4	Protein	IL-5
T5	Protein	CD4
*	Equiv T3 T4
T26	Entity	promoter
E1	Gene_expression Theme:T1
E2	Regulation Cause:T1 Theme:E3
E3	Gene_expression Theme:T2
E4	Gene_expression Theme:T3
E5	Positive_regulation Cause:T1 Theme:E6
E6	Positive_regulation Site:T26 Theme:T3
E7	Positive_regulation Cause:T1 Theme:E8
E8	Gene_expression Theme:T3
E9	Negative_regulation Theme:E10
E10	Positive_regulation Site:T26 Theme:T3
E11	Gene_expression Theme:T1
E12	Gene_expression Theme:T3
E13	Positive_regulation Site:T26 Theme:T3
E14	Positive_regulation Cause:E11 Site:T26 Theme:T3
E15	Gene_expression Theme:T1
E16	Positive_regulation Theme:E15
E17	Negative_regulation Theme:E15
E18	Gene_expression Theme:T1
E19	Negative_regulation Theme:T1
M1	Negation E4
M2	Negation E12
M3	Negation E17
