T1	Protein	vascular cell adhesion molecule-1
T2	Protein	tumor necrosis factor-alpha
T3	Protein	TNF
T5	Protein	VCAM-1
T7	Protein	ntercellular adhesion molecule-1
T8	Protein	ICAM-1
*	Equiv T2 T3
*	Equiv T7 T8
*	Equiv T1 T5
E1	Negative_regulation Theme:E2
E2	Positive_regulation Theme:T1
E3	Positive_regulation Theme:T1
E4	Regulation Theme:E7
E5	Regulation Theme:E6
E6	Positive_regulation Cause:T2 Theme:T7
E7	Positive_regulation Cause:T2 Theme:T1
E8	Negative_regulation Theme:E15
E9	Negative_regulation Theme:E13
E10	Negative_regulation Theme:E14
E11	Negative_regulation Theme:E12
E12	Positive_regulation Cause:T2 Theme:E19
E13	Positive_regulation Cause:T2 Theme:E16
E14	Positive_regulation Cause:T2 Theme:E17
E15	Positive_regulation Cause:T2 Theme:E18
E16	Transcription Theme:T1
E17	Gene_expression Theme:T1
E18	Transcription Theme:T7
E19	Gene_expression Theme:T7
E20	Positive_regulation Theme:T1
E21	Regulation Theme:E20
E22	Positive_regulation Theme:T1
E23	Positive_regulation Cause:T2 Theme:T7
E24	Negative_regulation Theme:E23
E25	Negative_regulation Theme:E26
E26	Positive_regulation Cause:T2 Theme:T1
E27	Regulation Theme:E26
E28	Negative_regulation Theme:E29
E29	Positive_regulation Cause:T2 Theme:T1
M1	Speculation E4
M2	Speculation E5
M3	Negation E8
M4	Negation E11
M5	Negation E24
