T1	Protein	vitamin D receptors
T2	Protein	VDR
T4	Protein	IL-4
T7	Protein	25-hydroxyvitamin D3 24-hydroxylase
T8	Protein	CD40 Ag
T10	Protein	24-hydroxylase
*	Equiv T1 T2
*	Equiv T4 T4
E1	Gene_expression Theme:T1
E2	Positive_regulation Theme:E5
E3	Positive_regulation Theme:E4
E4	Positive_regulation Theme:T1
E5	Binding Theme:T1
E6	Positive_regulation Theme:E7
E7	Positive_regulation Theme:E8
E8	Gene_expression Theme:T1
E9	Positive_regulation Theme:E10
E10	Transcription Theme:T7
E11	Binding Theme:T8
E12	Positive_regulation Theme:E15
E13	Positive_regulation Theme:E14
E14	Positive_regulation Theme:T1
E15	Positive_regulation Theme:E16
E16	Positive_regulation Theme:T10
M1	Negation E1
M2	Negation E9
M3	Speculation E12
M4	Speculation E13
M5	Speculation E14
M6	Speculation E15
M7	Speculation E16
