T1	Protein	MNDA
T2	Protein	myeloid cell nuclear differentiation antigen
T4	Protein	PU.1
T5	Protein	Sp1
*	Equiv T1 T2
E1	Regulation Theme:T2
E2	Gene_expression Theme:T2
E3	Positive_regulation Theme:E4
E4	Regulation Theme:E5
E5	Gene_expression Theme:T2
E6	Regulation Theme:T2
E7	Positive_regulation Theme:E8
E8	Gene_expression Theme:T2
E9	Gene_expression Theme:T2
E10	Regulation Theme:E9
M1	Speculation E7
