T1	Protein	p50
T2	Protein	TNF
T3	Protein	tumor necrosis factor
T4	Protein	CD14 receptor
T12	Protein	kappa light chain
*	Equiv T2 T3
T27	Entity	GGGGACTTTCCG
E1	Positive_regulation Theme:T1
E2	Gene_expression Theme:T3
E3	Negative_regulation Theme:E2
E4	Gene_expression Theme:T4
E5	Binding Theme:T1
E6	Binding Theme:T1
E7	Binding Theme:T1
E8	Positive_regulation Theme:T1
E9	Binding Theme:T1
E10	Binding Theme:T1
E11	Binding Theme:T1
E12	Positive_regulation Theme:T1
E13	Positive_regulation Theme:T1
E14	Binding Theme:T1
E15	Binding Theme:T1
E16	Binding Site:T27 Theme:T12 Theme2:T1
E17	Binding Site:T27 Theme:T12 Theme2:T1
E18	Negative_regulation Theme:E16
E19	Negative_regulation Theme:E17
E20	Positive_regulation Theme:T1
E21	Regulation Theme:E20
M1	Negation E7
M2	Negation E9
M3	Negation E14
M4	Negation E15
M5	Negation E16
M6	Negation E17
