T1	Protein	A-MYB
T6	Protein	c-MYC
T10	Entity	DNA binding domain
T20	Entity	N-terminal domain
E1	Binding Site:T10 Theme:T1
E2	Gene_expression Theme:T1
E3	Regulation Theme:T1
E4	Positive_regulation Theme:T1
E5	Positive_regulation Theme:T1
E6	Positive_regulation Theme:T1
E7	Binding Theme:T1
E8	Negative_regulation Theme:T1
E9	Binding Site:T20 Theme:T1
E10	Positive_regulation Theme:T1
M1	Speculation E3
M2	Negation E4
M3	Negation E6
M4	Speculation E10
