T1	Protein	Stat5
T2	Protein	Stat6
T5	Protein	Prolactin
T7	Protein	interleukin-4
T8	Protein	IL-4
T14	Protein	glucocorticoid receptor
T21	Protein	VP16
*	Equiv T7 T8
T34	Entity	transactivation domain
E1	Positive_regulation Theme:T2
E2	Positive_regulation Theme:T1
E3	Positive_regulation Cause:T5 Theme:T1
E4	Positive_regulation Cause:T7 Theme:T2
E5	Positive_regulation Theme:T2
E6	Negative_regulation Theme:E5
E7	Positive_regulation Cause:T7 Theme:T2
E8	Positive_regulation Theme:T2
E9	Positive_regulation Cause:T14 Theme:T2
E10	Regulation Cause:T7 Site:T34 Theme:T2
E11	Positive_regulation Cause:E12 Theme:E10
E12	Binding Site:T34 Theme:T2
M1	Speculation E5
M2	Negation E6
M3	Negation E11
