T1	Protein	Spi-B
T3	Protein	Spi-1
T4	Protein	PU.1
T8	Protein	deltaSpi-B
T9	Protein	deltaspi-B
T10	Protein	spi-B
T11	Protein	DeltaSpi-B
T12	Protein	delta Spi-B
*	Equiv T3 T4
T20	Entity	cytoplasmic cellular extracts
E1	Gene_expression Theme:T1
E2	Binding Theme:T1
E3	Transcription Theme:T10
E4	Transcription Theme:T9
E5	Binding Theme:T11
E6	Localization AtLoc:T20 Theme:T11
E7	Regulation Theme:T1
M1	Negation E5
M2	Speculation E7
