T1	Protein	tumor necrosis factor-alpha
T2	Protein	interleukin (IL)-8
T3	Protein	-6
T4	Protein	matrix metalloproteinase-9
T5	Protein	IL-8
E1	Gene_expression Theme:T1
E2	Gene_expression Theme:T3
E3	Gene_expression Theme:T4
E4	Gene_expression Theme:T2
E5	Negative_regulation Theme:E8
E6	Negative_regulation Theme:E7
E7	Localization Theme:T5
E8	Localization Theme:T1
E9	Positive_regulation Theme:E10
E10	Localization Theme:T5
E11	Gene_expression Theme:T5
E12	Positive_regulation Theme:E11
M1	Negation E11
