T1	Protein	Thrombin
T2	Protein	p65
T3	Protein	ICAM-1
T4	Protein	thrombin
T6	Protein	CD54
T14	Protein	E1B
T19	Protein	Rel A
T21	Protein	Thrombin receptor
T22	Protein	proteolytically activated receptor-1
*	Equiv T3 T6
*	Equiv T2 T19
T41	Entity	promoter
T44	Entity	downstream NF-kappa B site
E1	Positive_regulation Cause:T1 Theme:E2
E2	Binding Theme:T2
E3	Positive_regulation Cause:E1 Theme:E4
E4	Gene_expression Theme:T3
E5	Localization Theme:T4
E6	Positive_regulation Cause:T4 Theme:E7
E7	Gene_expression Theme:T3
E8	Positive_regulation Theme:E10
E9	Positive_regulation Theme:T3
E10	Gene_expression Theme:T3
E11	Negative_regulation Theme:E12
E12	Positive_regulation Site:T41 Theme:T3
E13	Positive_regulation Cause:T4 Theme:E14
E14	Binding Theme:T2 Site2:T44 Theme2:T3
E15	Positive_regulation Theme:E17
E16	Positive_regulation Cause:T4 Theme:E17
E17	Gene_expression Theme:T3
E18	Positive_regulation Cause:T4 Theme:E19
E19	Gene_expression Theme:T3
E20	Binding Theme:T2 Site2:T41 Theme2:T3
E21	Positive_regulation Cause:E22 Theme:E20
E22	Positive_regulation Theme:T22
