T1	Protein	STAT1
T2	Protein	p50
T5	Protein	I kappa B alpha
T6	Protein	IL-2
T7	Protein	Rch1
T10	Entity	nuclear
E1	Regulation Theme:E2
E2	Localization Theme:T1 ToLoc:T10
E3	Positive_regulation Theme:E4
E4	Localization Theme:T1 ToLoc:T10
E5	Negative_regulation Theme:E4
E6	Negative_regulation Theme:E7
E7	Localization Theme:T1 ToLoc:T10
E8	Negative_regulation Cause:E6 Theme:E13
E9	Negative_regulation Theme:E12
E10	Negative_regulation Cause:E6 Theme:E12
E11	Negative_regulation Theme:E13
E12	Gene_expression Theme:T6
E13	Gene_expression Theme:T5
E14	Regulation Theme:E12
E15	Regulation Theme:E13
E16	Gene_expression Theme:T7
E17	Positive_regulation Theme:E18
E18	Localization Theme:T1 ToLoc:T10
E19	Regulation Theme:E18
