T1	Protein	E2F-1
T2	Protein	uracil-DNA glycosylase
T5	Protein	UDG
T10	Protein	DP1
*	Equiv T2 T5
T18	Entity	promoter
E1	Regulation Cause:T1 Theme:T2
E2	Gene_expression Theme:T1
E3	Positive_regulation Cause:E2 Site:T18 Theme:T2
E4	Positive_regulation Theme:E3
E5	Binding Theme:T1
E6	Binding Theme:T10
E7	Binding Theme:T1 Theme2:T10
E8	Gene_expression Theme:T2
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T2
E11	Gene_expression Theme:T2
E12	Positive_regulation Theme:E11
