T1	Protein	CD28
T2	Protein	IL-2
T18	Protein	I-kappaBalpha
T19	Protein	I-kappaBbeta
E1	Positive_regulation Theme:T1
E2	Positive_regulation Cause:E4 Theme:E3
E3	Localization Theme:T2
E4	Positive_regulation Cause:E1 Theme:T2
E5	Positive_regulation Cause:E1 Theme:E6
E6	Positive_regulation Theme:T2
E7	Positive_regulation Theme:E8
E8	Localization Theme:T2
E9	Binding Theme:T1
E10	Positive_regulation Cause:E9 Theme:E11
E11	Localization Theme:T2
E12	Positive_regulation Theme:T2
E13	Regulation Theme:E14
E14	Positive_regulation Cause:T1 Theme:E15
E15	Gene_expression Theme:T2
E16	Gene_expression Theme:T2
E17	Positive_regulation Theme:E16
E18	Localization Theme:T2
E19	Positive_regulation Theme:E20
E20	Transcription Theme:T2
E21	Positive_regulation Cause:E22 Theme:E19
E22	Positive_regulation Theme:T2
E23	Binding Theme:T1
E24	Regulation Cause:E28 Theme:E27
E25	Regulation Cause:E28 Theme:E26
E26	Gene_expression Theme:T18
E27	Gene_expression Theme:T19
E28	Binding Theme:T1
E29	Binding Theme:T1
E30	Regulation Theme:E31
E31	Regulation Theme:E32
E32	Localization Theme:T2
M1	Negation E5
M2	Negation E24
M3	Negation E25
