T1	Protein	hematopoietic tyrosine phosphatase
T2	Protein	HePTP
T3	Protein	hematopoietic protein-tyrosine phosphatase
T5	Protein	interleukin-2
T8	Protein	Erk1
T9	Protein	2
*	Equiv T1 T2 T2 T3
E1	Gene_expression Theme:T1
E2	Positive_regulation Theme:T1
E3	Positive_regulation Theme:E4
E4	Binding Theme:T5
E5	Regulation Cause:T1 Theme:T9
E6	Regulation Cause:T1 Theme:T8
E7	Negative_regulation Cause:T1 Theme:E9
E8	Negative_regulation Cause:T1 Theme:E10
E9	Positive_regulation Theme:T9
E10	Positive_regulation Theme:T8
E11	Binding Theme:T1
M1	Negation E11
