T1	Protein	v-abl
T3	Protein	BCL-2
T5	Protein	kappa
T6	Protein	lambda light-chain
T7	Protein	RAG-1
T8	Protein	RAG-2
E1	Gene_expression Theme:T3
E2	Negative_regulation Theme:T1
E3	Positive_regulation Theme:E6
E4	Positive_regulation Theme:E5
E5	Transcription Theme:T7
E6	Transcription Theme:T8
E7	Positive_regulation Cause:E9 Theme:E3
E8	Positive_regulation Cause:E9 Theme:E4
E9	Negative_regulation Theme:T1
