T1	Protein	IL-2
T2	Protein	CD28
T4	Protein	interleukin-2
*	Equiv T1 T4
E1	Gene_expression Theme:T4
E2	Positive_regulation Cause:T2 Theme:E1
E3	Positive_regulation Theme:E2
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T4
E6	Positive_regulation Theme:E8
E7	Positive_regulation Theme:E9
E8	Positive_regulation Cause:T2 Theme:T2
E9	Gene_expression Theme:T4
E10	Positive_regulation Theme:E11
E11	Gene_expression Theme:T4
