T1	Protein	glucocorticoid receptor
T2	Protein	GR
T7	Protein	androgen receptor
T8	Protein	AR
T12	Protein	VP16
T13	Protein	E1A
T16	Protein	GIG18
*	Equiv T1 T2
*	Equiv T7 T8
T24	Entity	N-terminal domain
E1	Positive_regulation Site:T24 Theme:T1
E2	Positive_regulation Theme:E3
E3	Gene_expression Theme:T1
E4	Gene_expression Theme:T1
E5	Positive_regulation Theme:E4
E6	Gene_expression Theme:T1
E7	Gene_expression Theme:T16
E8	Positive_regulation Cause:T7 Theme:T16
E9	Positive_regulation Cause:T1 Theme:T16
E10	Positive_regulation Theme:T16
