T1	Protein	early growth response 1
T3	Protein	EGR-1
*	Equiv T1 T3
E1	Positive_regulation Theme:E2
E2	Transcription Theme:T1
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Regulation Theme:E6
E6	Transcription Theme:T1
E7	Positive_regulation Theme:E8
E8	Transcription Theme:T1
E9	Regulation Theme:E10
E10	Gene_expression Theme:T1
E11	Regulation Theme:E12
E12	Positive_regulation Theme:E13
E13	Gene_expression Theme:T1
M1	Negation E5
M2	Negation E11
