T1	Protein	CD4
T2	Protein	tumor necrosis factor
T3	Protein	interleukin-7
T5	Protein	Tumor necrosis factor
T6	Protein	TNF
T8	Protein	IL-7
T10	Protein	p50
T11	Protein	p65
T13	Protein	p75 TNF receptor
*	Equiv T3 T8
*	Equiv T5 T6
E1	Localization Theme:T5
E2	Localization Theme:T3
E3	Positive_regulation Cause:T5 Theme:T11
E4	Positive_regulation Cause:T5 Theme:T10
E5	Positive_regulation Cause:T3 Theme:E6
E6	Gene_expression Theme:T13
E7	Gene_expression Theme:T5
E8	Gene_expression Theme:T1
E9	Gene_expression Theme:T5
M1	Negation E7
M2	Speculation E9
