T1	Protein	Fas
T2	Protein	p50
T3	Protein	p65
T5	Protein	CD95
T6	Protein	Fas ligand
T7	Protein	CD95L
T9	Protein	FasL
T12	Protein	fas
T17	Protein	Sp1
T27	Protein	IkappaB-alpha
*	Equiv T6 T7
*	Equiv T1 T5
T32	Entity	promoter
E1	Positive_regulation Theme:E2
E2	Regulation Site:T32 Theme:T1
E3	Positive_regulation Cause:E5 Theme:E2
E4	Positive_regulation Cause:E6 Theme:E2
E5	Positive_regulation Theme:T2
E6	Positive_regulation Theme:T3
E7	Binding Theme:T1 Theme2:T6
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T1
E10	Positive_regulation Theme:T1
E11	Positive_regulation Theme:E12
E12	Positive_regulation Theme:T1
E13	Gene_expression Theme:T1
E14	Gene_expression Theme:T1
E15	Positive_regulation Theme:T1
E16	Positive_regulation Theme:E17
E17	Positive_regulation Theme:T12
E18	Binding Theme:T17
E19	Positive_regulation Theme:E21
E20	Positive_regulation Theme:E22
E21	Binding Theme:T3
E22	Binding Theme:T2
E23	Binding Theme:T17
E24	Negative_regulation Theme:E23
E25	Positive_regulation Site:T32 Theme:T12
E26	Positive_regulation Theme:E27
E27	Positive_regulation Site:T32 Theme:T12
M1	Speculation E13
