T1	Protein	IL-4
T7	Protein	C/EBPbeta
T8	Protein	NF-IL6
T9	Protein	C/EBPdelta
T10	Protein	NF-IL6beta
T11	Protein	NF-ATc
T12	Protein	NF-ATp
*	Equiv T9 T10
*	Equiv T7 T8
E1	Localization Theme:T1
E2	Regulation Theme:E3
E3	Gene_expression Theme:T1
E4	Binding Theme:T1
E5	Gene_expression Theme:T1
E6	Regulation Theme:E7
E7	Regulation Theme:E8
E8	Gene_expression Theme:T1
M1	Negation E1
M2	Speculation E2
M3	Speculation E3
M4	Speculation E4
M5	Speculation E6
