T1	Protein	ICAM-1
T2	Protein	Intercellular adhesion molecule 1
T9	Protein	p65
T10	Protein	Rel A
*	Equiv T9 T10
*	Equiv T1 T2
T22	Entity	nuclear
E1	Positive_regulation Theme:E2
E2	Positive_regulation Theme:T2
E3	Regulation Theme:E4
E4	Gene_expression Theme:T2
E5	Gene_expression Theme:T2
E6	Positive_regulation Theme:T2
E7	Positive_regulation Theme:E8
E8	Gene_expression Theme:T2
E9	Positive_regulation Theme:E11
E10	Regulation Theme:E11
E11	Localization Theme:T9 ToLoc:T22
E12	Regulation Theme:E13
E13	Positive_regulation Theme:E14
E14	Positive_regulation Theme:T2
M1	Speculation E3
M2	Speculation E5
M3	Negation E6
M4	Speculation E13
M5	Speculation E14
