T1	Protein	interleukin 2
T2	Protein	IL-2
*	Equiv T1 T2
T18	Entity	promoter
T21	Entity	their corresponding sites
E1	Negative_regulation Theme:T1
E2	Transcription Theme:T1
E3	Regulation Theme:E2
E4	Negative_regulation Theme:E5
E5	Transcription Theme:T1
E6	Binding Site:T18 Theme:T1
E7	Negative_regulation Theme:E8
E8	Binding Site:T21 Theme:T1
E9	Positive_regulation Theme:E10
E10	Negative_regulation Site:T18 Theme:T1
E11	Negative_regulation Theme:T1
E12	Negative_regulation Theme:T1
E13	Negative_regulation Theme:E14
E14	Transcription Theme:T1
E15	Negative_regulation Theme:E14
E16	Positive_regulation Theme:E15
M1	Speculation E4
M2	Speculation E9
M3	Speculation E13
