T1	Protein	interleukin 9
T3	Protein	IL-9
T10	Protein	c-Jun
*	Equiv T1 T3
T23	Entity	promoter
E1	Positive_regulation Theme:E2
E2	Positive_regulation Theme:T1
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Gene_expression Theme:T1
E6	Regulation Theme:E5
E7	Gene_expression Theme:T1
E8	Gene_expression Theme:T1
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T1
E11	Positive_regulation Site:T23 Theme:T1
E12	Binding Theme:T10
E13	Negative_regulation Theme:E12
E14	Positive_regulation Cause:T10 Theme:E15
E15	Gene_expression Theme:T1
M1	Speculation E3
