T1	Protein	alpha 4 integrin
T2	Protein	alpha 4 integrins
T3	Protein	alpha 4
T8	Protein	GA-binding protein alpha
T9	Protein	GABP alpha
*	Equiv T8 T9
T14	Entity	promoter
E1	Regulation Site:T14 Theme:T1
E2	Regulation Theme:E3
E3	Gene_expression Theme:T2
E4	Gene_expression Theme:T2
E5	Positive_regulation Theme:E6
E6	Transcription Theme:T2
E7	Gene_expression Theme:T2
E8	Positive_regulation Theme:E6
E9	Gene_expression Theme:T2
E10	Positive_regulation Theme:E12
E11	Binding Theme:T9
E12	Positive_regulation Site:T14 Theme:T3
E13	Positive_regulation Theme:E14
E14	Transcription Theme:T2
E15	Regulation Theme:E16
E16	Binding Theme:T9
E17	Positive_regulation Theme:T2
E18	Binding Site:T14 Theme:T3
E19	Regulation Theme:E20
E20	Gene_expression Theme:T1
M1	Speculation E2
M2	Negation E4
M3	Negation E8
M4	Negation E9
M5	Negation E15
M6	Speculation E19
