T1	Protein	interleukin-2
T2	Protein	IL-2
T4	Protein	chloramphenicol acetyltransferase
T5	Protein	CAT
*	Equiv T1 T2
*	Equiv T4 T5
T7	Entity	promoter
E1	Binding Site:T7 Theme:T1
E2	Positive_regulation Theme:E3
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Binding Site:T7 Theme:T1
E6	Positive_regulation Theme:E5
E7	Positive_regulation Theme:E8
E8	Transcription Theme:T4
M1	Speculation E2
M2	Negation E7
