T1	Protein	IkappaBalpha
T2	Protein	tumor necrosis factor alpha
T3	Protein	IL-10
T4	Protein	-11
T6	Protein	matrix metalloproteinases 1
T7	Protein	3
E1	Positive_regulation Theme:E2
E2	Negative_regulation Theme:T1
E3	Gene_expression Theme:T2
E4	Regulation Theme:T3
E5	Regulation Theme:E3
E6	Regulation Theme:T4
E7	Gene_expression Theme:T1
E8	Positive_regulation Theme:E7
E9	Negative_regulation Cause:E8 Theme:E12
E10	Negative_regulation Cause:E8 Theme:E11
E11	Gene_expression Theme:T7
E12	Gene_expression Theme:T6
E13	Regulation Cause:E8 Theme:T6
E14	Regulation Cause:E8 Theme:T7
M1	Negation E4
M2	Negation E6
M3	Negation E13
M4	Negation E14
