T1	Protein	activation-inducer molecule
T2	Protein	CD69
T3	Protein	activation inducer molecule
T4	Protein	AIM
T11	Protein	c-fos
T12	Protein	c-jun
T13	Protein	Fos
T14	Protein	c-Fos
*	Equiv T1 T2 T2 T3 T4 T4
T19	Entity	cell-surface
E1	Positive_regulation Theme:E2
E2	Localization AtLoc:T19 Theme:T1
E3	Positive_regulation Theme:E6
E4	Positive_regulation Theme:E5
E5	Transcription Theme:T11
E6	Transcription Theme:T12
E7	Binding Theme:T14
E8	Positive_regulation Theme:E7
