T1	Protein	porphobilinogen deaminase
T2	Protein	PBGD
T4	Protein	erythropoietin receptor
T5	Protein	GATA-1
*	Equiv T1 T2
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E8
E4	Positive_regulation Theme:E7
E5	Positive_regulation Theme:E6
E6	Transcription Theme:T1
E7	Transcription Theme:T4
E8	Transcription Theme:T5
E9	Transcription Theme:T5
E10	Transcription Theme:T4
E11	Transcription Theme:T1
E12	Regulation Theme:E11
E13	Regulation Theme:E9
E14	Regulation Theme:E10
E15	Positive_regulation Theme:T1
E16	Positive_regulation Theme:T5
E17	Regulation Theme:T1
E18	Regulation Theme:T5
E19	Positive_regulation Theme:T5
M1	Negation E12
M2	Negation E13
M3	Negation E14
M4	Negation E18
M5	Negation E19
