T1	Protein	interleukin-2 receptor alpha
T2	Protein	p50
T3	Protein	p65
T5	Protein	KBF1
T8	Protein	interleukin-2 (IL-2) receptor alpha chain
T9	Protein	IL-2R alpha
T12	Protein	IL-2
*	Equiv T8 T9
T16	Entity	nucleus
E1	Gene_expression Theme:T2
E2	Localization AtLoc:T16 Theme:T2
E3	Binding Theme:T2
E4	Gene_expression Theme:T5
E5	Gene_expression Theme:T5
E6	Gene_expression Theme:T8
E7	Gene_expression Theme:T12
