T1	Protein	FcepsilonRIIb receptor
T2	Protein	CD23
T3	Protein	CD23 receptor
T7	Protein	IkappaBalpha
T10	Protein	p65
T11	Protein	p50
T16	Protein	TNF-alpha
T17	Protein	IL-1beta
*	Equiv T1 T2
E1	Binding Theme:T3
E2	Binding Theme:T1
E3	Gene_expression Theme:T1
E4	Phosphorylation Theme:T7
E5	Protein_catabolism Theme:T7
E6	Binding Theme:T1
E7	Positive_regulation Cause:T1 Theme:T10
E8	Positive_regulation Cause:T1 Theme:T11
E9	Phosphorylation Theme:T7
E10	Protein_catabolism Theme:T7
E11	Regulation Theme:E12
E12	Phosphorylation Theme:T7
E13	Protein_catabolism Theme:T7
E14	Positive_regulation Theme:T16
E15	Positive_regulation Theme:T17
M1	Speculation E3
M2	Speculation E4
M3	Speculation E5
M4	Negation E11
