T1	Protein	STAT1
T4	Protein	FcgammaRI
T5	Protein	ICAM-1
T6	Protein	IFN regulatory factor-1
T7	Protein	fibronectin
T11	Protein	IFN-gamma
T29	Entity	Y701
T30	Entity	S727
E1	Positive_regulation Theme:T1
E2	Positive_regulation Theme:E1
E3	Positive_regulation Theme:T1
E4	Positive_regulation Theme:E3
E5	Binding Theme:T1
E6	Positive_regulation Theme:T5
E7	Positive_regulation Theme:T4
E8	Positive_regulation Theme:T1
E9	Positive_regulation Theme:E10
E10	Binding Theme:T1
E11	Positive_regulation Theme:E12
E12	Positive_regulation Theme:T1
E13	Phosphorylation Site:T30 Theme:T1
E14	Phosphorylation Site:T29 Theme:T1
E15	Negative_regulation Theme:E16
E16	Binding Theme:T1
E17	Positive_regulation Theme:T1
E18	Regulation Cause:E17 Theme:E21
E19	Regulation Cause:E17 Theme:E20
E20	Gene_expression Theme:T4
E21	Gene_expression Theme:T5
M1	Speculation E2
