T1	Protein	tumor necrosis factor-alpha
T2	Protein	TNF
T3	Protein	vascular cell adhesion molecule 1
T4	Protein	VCAM-1
T5	Protein	interleukin-4
T6	Protein	IL-4
T8	Protein	E-selectin
*	Equiv T1 T2
*	Equiv T3 T4
*	Equiv T5 T6
E1	Positive_regulation Cause:T5 Theme:T3
E2	Negative_regulation Theme:E4
E3	Negative_regulation Theme:E5
E4	Positive_regulation Cause:T1 Theme:T3
E5	Positive_regulation Cause:T1 Theme:T8
E6	Transcription Theme:T3
