T1	Protein	IL-5
T22	Entity	segment
E1	Gene_expression Theme:T1
E2	Gene_expression Theme:T1
E3	Gene_expression Theme:T1
E4	Positive_regulation Theme:E3
E5	Gene_expression Theme:T1
E6	Positive_regulation Theme:E5
E7	Gene_expression Theme:T1
E8	Transcription Theme:T1
E9	Positive_regulation Theme:E8
E10	Positive_regulation Site:T22 Theme:T1
E11	Transcription Theme:T1
E12	Gene_expression Theme:T1
E13	Gene_expression Theme:T1
E14	Regulation Cause:E15 Theme:E13
E15	Transcription Theme:T1
E16	Positive_regulation Theme:E17
E17	Transcription Theme:T1
E18	Positive_regulation Theme:E19
E19	Gene_expression Theme:T1
M1	Speculation E2
M2	Negation E11
M3	Speculation E16
