T1	Protein	p24
T4	Protein	granulocyte-macrophage colony-stimulating factor
T5	Protein	interleukin-6
T7	Protein	TBP-1
E1	Negative_regulation Theme:E2
E2	Positive_regulation Theme:E3
E3	Gene_expression Theme:T1
E4	Negative_regulation Theme:E5
E5	Gene_expression Theme:T1
E6	Negative_regulation Theme:E12
E7	Negative_regulation Theme:E11
E8	Negative_regulation Theme:E10
E9	Gene_expression Theme:T1
E10	Positive_regulation Cause:T5 Theme:E9
E11	Positive_regulation Cause:T4 Theme:E9
E12	Positive_regulation Theme:E9
E13	Negative_regulation Theme:E14
E14	Gene_expression Theme:T1
E15	Localization Theme:T7
E16	Positive_regulation Theme:E15
