T1	Protein	interleukin (IL)-1alpha
T2	Protein	IL-1beta
T3	Protein	IL-4
T4	Protein	vascular cell adhesion molecule-1
T5	Protein	VCAM-1
T6	Protein	E-selectin
T7	Protein	intercellular adhesion molecule-1
*	Equiv T4 T5
E1	Gene_expression Theme:T6
E2	Gene_expression Theme:T7
E3	Gene_expression Theme:T4
E4	Transcription Theme:T4
E5	Negative_regulation Theme:E9
E6	Negative_regulation Theme:E8
E7	Negative_regulation Theme:E10
E8	Gene_expression Theme:T4
E9	Gene_expression Theme:T6
E10	Gene_expression Theme:T7
E11	Gene_expression Theme:T4
E12	Negative_regulation Theme:E11
E13	Negative_regulation Theme:T4
M1	Speculation E3
M2	Speculation E4
