T1	Protein	IkappaBalpha
T2	Protein	I(kappa)B(alpha)
T10	Protein	IkappaBbeta
T19	Entity	nuclear
T32	Entity	nucleus
E1	Gene_expression Theme:T1
E2	Negative_regulation Theme:T2
E3	Positive_regulation Theme:E2
E4	Positive_regulation Cause:E6 Theme:E5
E5	Gene_expression Theme:T2
E6	Positive_regulation Theme:T2
E7	Localization Theme:T2 ToLoc:T19
E8	Positive_regulation Theme:T2
E9	Positive_regulation Theme:E10
E10	Positive_regulation Theme:T2
E11	Positive_regulation Theme:T2
E12	Gene_expression Theme:T2
E13	Localization AtLoc:T19 Theme:T2
E14	Regulation Cause:E15 Theme:E13
E15	Localization AtLoc:T19 Theme:T10
E16	Localization AtLoc:T32 Theme:T2
M1	Negation E8
M2	Negation E14
