T1	Protein	interleukin-1 beta
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Regulation Theme:E1
E4	Negative_regulation Theme:E6
E5	Negative_regulation Cause:E7 Theme:E6
E6	Gene_expression Theme:T1
E7	Negative_regulation Theme:T1
E8	Transcription Theme:T1
E9	Regulation Theme:E7
E10	Negative_regulation Theme:E11
E11	Positive_regulation Theme:E12
E12	Gene_expression Theme:T1
E13	Positive_regulation Theme:E12
E14	Positive_regulation Theme:E13
E15	Negative_regulation Theme:E16
E16	Transcription Theme:T1
E17	Regulation Theme:E15
E18	Positive_regulation Theme:T1
E19	Positive_regulation Theme:T1
E20	Negative_regulation Theme:E19
M1	Speculation E9
M2	Negation E17
M3	Negation E20
