T1	Protein	PU.1
T2	Protein	macrophage colony-stimulating factor receptor
T3	Protein	macrophage colony-stimulating factor (M-CSF) receptor
T4	Protein	M-CSF receptor
T24	Entity	promoter
T26	Entity	specific site
E1	Positive_regulation Cause:T1 Theme:E2
E2	Gene_expression Theme:T2
E3	Gene_expression Theme:T3
E4	Regulation Theme:E3
E5	Positive_regulation Theme:T4
E6	Binding Theme:T1 Site2:T24 Theme2:T4
E7	Positive_regulation Cause:T1 Site:T24 Theme:T4
E8	Binding Theme:T1 Site2:T24 Theme2:T4
E9	Binding Theme:T1 Site2:T24 Theme2:T4
E10	Negative_regulation Theme:E11
E11	Binding Site:T26 Theme:T4 Theme2:T1
E12	Negative_regulation Cause:E10 Site:T24 Theme:T4
E13	Positive_regulation Cause:T1 Site:T24 Theme:T4
M1	Speculation E6
M2	Speculation E7
