T1	Protein	I kappa B alpha
T5	Protein	RelA
T6	Protein	p50
T8	Protein	tumor necrosis factor alpha
T9	Protein	TNF-alpha
*	Equiv T8 T9
E1	Phosphorylation Theme:T1
E2	Phosphorylation Theme:T1
E3	Protein_catabolism Theme:T1
E4	Regulation Theme:E5
E5	Phosphorylation Theme:T1
E6	Positive_regulation Theme:E7
E7	Phosphorylation Theme:T1
E8	Regulation Theme:E6
E9	Positive_regulation Theme:T6
E10	Positive_regulation Theme:T5
E11	Regulation Theme:E6
E12	Negative_regulation Theme:E13
E13	Positive_regulation Cause:T8 Theme:E14
E14	Phosphorylation Theme:T1
E15	Phosphorylation Theme:T1
E16	Phosphorylation Theme:T1
E17	Positive_regulation Theme:E16
E18	Positive_regulation Cause:T8 Theme:E16
E19	Positive_regulation Theme:E21
E20	Positive_regulation Cause:T8 Theme:E21
E21	Phosphorylation Theme:T1
E22	Protein_catabolism Theme:T1
E23	Positive_regulation Theme:E25
E24	Positive_regulation Cause:T8 Theme:E25
E25	Protein_catabolism Theme:T1
E26	Phosphorylation Theme:T1
E27	Positive_regulation Theme:E26
E28	Regulation Theme:E30
E29	Regulation Cause:E27 Theme:E30
E30	Positive_regulation Theme:E31
E31	Protein_catabolism Theme:T1
M1	Speculation E4
M2	Negation E8
M3	Negation E11
M4	Speculation E28
M5	Speculation E29
