T1	Protein	Interleukin (IL)-10
T2	Protein	IL-10
T3	Protein	IL-4
T4	Protein	interleukin (IL)-10
T5	Protein	IL-1 beta
T6	Protein	IL-6
T7	Protein	IL-8
T8	Protein	tumor necrosis factor (TNF)-alpha
T9	Protein	TNF alpha
T11	Protein	NF-IL-6
T12	Protein	AP-1
T13	Protein	AP-2
T14	Protein	GR
T15	Protein	CREB
T16	Protein	Oct-1
T17	Protein	Sp-1
E1	Negative_regulation Theme:E5
E2	Negative_regulation Theme:E8
E3	Negative_regulation Theme:E6
E4	Negative_regulation Theme:E7
E5	Positive_regulation Theme:E12
E6	Positive_regulation Theme:E9
E7	Positive_regulation Theme:E10
E8	Positive_regulation Theme:E11
E9	Gene_expression Theme:T6
E10	Gene_expression Theme:T7
E11	Gene_expression Theme:T5
E12	Gene_expression Theme:T8
E13	Regulation Cause:T2 Theme:T13
E14	Regulation Cause:T2 Theme:T12
E15	Regulation Cause:T2 Theme:T15
E16	Regulation Cause:T2 Theme:T16
E17	Regulation Cause:T2 Theme:T14
E18	Regulation Cause:T2 Theme:T11
E19	Regulation Cause:T2 Theme:T17
M1	Negation E13
M2	Negation E14
M3	Negation E15
M4	Negation E16
M5	Negation E17
M6	Negation E18
M7	Negation E19
