T1	Protein	p50
T2	Protein	p65
T3	Protein	pro-interleukin-1beta
T4	Protein	pro-interleukin 1beta
T5	Protein	proIL-1beta
T7	Protein	fos
T8	Protein	CAT
T11	Protein	p52
T12	Protein	c-Rel
T13	Protein	Rel B
T14	Protein	c-Fos
T15	Protein	C-Jun
T16	Protein	C/EBPbeta
T17	Protein	NF-IL6
*	Equiv T16 T17
*	Equiv T4 T5
E1	Positive_regulation Cause:T2 Theme:E3
E2	Positive_regulation Cause:T1 Theme:E3
E3	Positive_regulation Theme:T3
E4	Regulation Theme:E5
E5	Transcription Theme:T5
E6	Positive_regulation Theme:E5
E7	Negative_regulation Theme:E8
E8	Positive_regulation Theme:E5
E9	Positive_regulation Theme:E10
E10	Positive_regulation Theme:E11
E11	Transcription Theme:T5
M1	Speculation E4
