T1	Protein	VCAM-1
T2	Protein	vascular cell adhesion molecule
*	Equiv T1 T2
E1	Regulation Theme:E2
E2	Positive_regulation Theme:E3
E3	Gene_expression Theme:T2
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T2
E6	Negative_regulation Theme:E7
E7	Positive_regulation Theme:E8
E8	Gene_expression Theme:T2
E9	Positive_regulation Theme:E10
E10	Positive_regulation Theme:E11
E11	Gene_expression Theme:T2
E12	Positive_regulation Theme:E13
E13	Gene_expression Theme:T2
E14	Negative_regulation Theme:E12
E15	Positive_regulation Theme:E16
E16	Gene_expression Theme:T2
