T1	Protein	CD14
T9	Protein	Sp1
T15	Protein	vitamin D3 receptor
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Positive_regulation Theme:E6
E6	Gene_expression Theme:T1
E7	Regulation Cause:E8 Theme:E5
E8	Positive_regulation Theme:E9
E9	Transcription Theme:T1
E10	Positive_regulation Theme:E11
E11	Positive_regulation Theme:T1
E12	Positive_regulation Theme:E13
E13	Gene_expression Theme:T1
E14	Binding Theme:T9
E15	Negative_regulation Theme:E16
E16	Binding Theme:T9
E17	Negative_regulation Theme:E18
E18	Positive_regulation Theme:E19
E19	Gene_expression Theme:T1
E20	Binding Theme:T15
E21	Positive_regulation Theme:T1
E22	Positive_regulation Theme:T9
M1	Speculation E3
M2	Speculation E4
M3	Negation E20
