T1	Protein	IL-2
T8	Entity	promoter
E1	Regulation Theme:E2
E2	Positive_regulation Site:T8 Theme:T1
E3	Positive_regulation Theme:E2
E4	Gene_expression Theme:T1
E5	Positive_regulation Theme:E4
E6	Positive_regulation Theme:E7
E7	Gene_expression Theme:T1
E8	Negative_regulation Theme:E9
E9	Transcription Theme:T1
E10	Binding Site:T8 Theme:T1
E11	Positive_regulation Site:T8 Theme:T1
E12	Negative_regulation Theme:E11
E13	Positive_regulation Site:T8 Theme:T1
E14	Positive_regulation Theme:E13
M1	Negation E1
M2	Speculation E6
