T1	Protein	interleukin 2
T2	Protein	Sp1
T3	Protein	EGR-1
T5	Protein	IL-2
*	Equiv T1 T5
T17	Entity	regulatory element
T21	Entity	promoter
E1	Binding Site:T17 Theme:T1 Theme2:T3
E2	Binding Site:T17 Theme:T1 Theme2:T2
E3	Positive_regulation Theme:T1
E4	Positive_regulation Site:T21 Theme:T1
E5	Binding Theme:T3
E6	Binding Theme:T2
E7	Gene_expression Theme:T2
E8	Positive_regulation Theme:T3
E9	Localization Theme:T1
E10	Binding Theme:T2
E11	Positive_regulation Theme:E12
E12	Localization Theme:T1
E13	Positive_regulation Theme:T3
E14	Positive_regulation Theme:E15
E15	Gene_expression Theme:T1
E16	Positive_regulation Site:T21 Theme:T1
E17	Regulation Site:T21 Theme:T1
M1	Negation E9
