T1	Protein	Tat
T2	Protein	interleukin-2
T5	Protein	IL-2
T7	Protein	chloramphenicol acetyltransferase
T11	Protein	phytohemagglutinin
T20	Protein	tat
T21	Protein	Tax
*	Equiv T2 T5
E1	Positive_regulation Cause:T1 Theme:E2
E2	Localization Theme:T2
E3	Regulation Cause:T1 Theme:E4
E4	Gene_expression Theme:T2
E5	Localization Theme:T2
E6	Gene_expression Theme:T1
E7	Localization Theme:T2
E8	Positive_regulation Theme:E7
E9	Regulation Cause:T1 Theme:E10
E10	Transcription Theme:T2
M1	Speculation E3
