T1	Protein	CD28
T2	Protein	interleukin-2
T4	Protein	IL-2
*	Equiv T2 T4
E1	Positive_regulation Cause:T1 Theme:E2
E2	Gene_expression Theme:T2
E3	Localization Theme:T2
E4	Gene_expression Theme:T2
E5	Regulation Theme:E4
E6	Positive_regulation Theme:T2
E7	Localization Theme:T2
E8	Negative_regulation Theme:E7
E9	Gene_expression Theme:T2
E10	Negative_regulation Theme:E9
E11	Positive_regulation Theme:E12
E12	Gene_expression Theme:T2
E13	Regulation Theme:E14
E14	Gene_expression Theme:T2
E15	Localization Theme:T2
E16	Negative_regulation Theme:E17
E17	Gene_expression Theme:T2
E18	Regulation Theme:E16
M1	Speculation E4
M2	Speculation E5
