T1	Protein	tumor necrosis factor alpha
T2	Protein	p50
T3	Protein	interleukin-2 receptor (IL-2R) alpha chain
T5	Protein	p65
T7	Protein	c-rel
T11	Protein	p105
T15	Protein	TNF-alpha
*	Equiv T1 T15
T32	Entity	nuclear
E1	Binding Theme:T2
E2	Positive_regulation Theme:E5
E3	Positive_regulation Theme:E4
E4	Binding Theme:T2
E5	Binding Theme:T5
E6	Binding Theme:T2 Theme2:T5
E7	Binding Theme:T2 Theme2:T7
E8	Binding Theme:T7
E9	Binding Theme:T2
E10	Localization Theme:T5 ToLoc:T32
E11	Localization Theme:T7 ToLoc:T32
E12	Positive_regulation Theme:E15
E13	Positive_regulation Theme:E17
E14	Positive_regulation Theme:E16
E15	Transcription Theme:T7
E16	Transcription Theme:T5
E17	Transcription Theme:T2
E18	Negative_regulation Theme:E10
E19	Negative_regulation Theme:E9
E20	Negative_regulation Theme:E8
E21	Negative_regulation Theme:E11
E22	Negative_regulation Theme:E5
E23	Negative_regulation Theme:E4
E24	Negative_regulation Theme:E28
E25	Negative_regulation Theme:E27
E26	Negative_regulation Theme:E29
E27	Localization Theme:T5
E28	Localization Theme:T7
E29	Binding Theme:T5 Theme2:T7
E30	Negative_regulation Theme:E11
E31	Negative_regulation Theme:E8
E32	Negative_regulation Theme:E4
E33	Negative_regulation Theme:E5
E34	Negative_regulation Theme:E9
E35	Negative_regulation Theme:E10
E36	Negative_regulation Cause:T1 Theme:E34
E37	Negative_regulation Cause:T1 Theme:E32
E38	Negative_regulation Cause:T1 Theme:E30
E39	Negative_regulation Cause:T1 Theme:E31
E40	Negative_regulation Cause:T1 Theme:E35
E41	Negative_regulation Cause:T1 Theme:E33
E42	Regulation Cause:T1 Theme:E46
E43	Regulation Cause:T1 Theme:E47
E44	Regulation Cause:T1 Theme:E49
E45	Regulation Cause:T1 Theme:E48
E46	Localization Theme:T5
E47	Localization Theme:T7
E48	Transcription Theme:T2
E49	Transcription Theme:T7
M1	Negation E14
M2	Negation E22
M3	Negation E23
