T1	Protein	IL-2
T2	Protein	Interleukin 2
T5	Protein	CD4
*	Equiv T1 T2
E1	Positive_regulation Theme:E3
E2	Negative_regulation Theme:E3
E3	Gene_expression Theme:T2
E4	Regulation Theme:E1
E5	Regulation Theme:E2
E6	Positive_regulation Theme:E7
E7	Gene_expression Theme:T2
E8	Positive_regulation Theme:T2
E9	Positive_regulation Theme:E10
E10	Positive_regulation Theme:T2
E11	Positive_regulation Theme:E13
E12	Transcription Theme:T2
E13	Positive_regulation Theme:E12
E14	Negative_regulation Theme:E15
E15	Gene_expression Theme:T2
E16	Regulation Theme:E17
E17	Gene_expression Theme:T2
E18	Regulation Theme:E19
E19	Gene_expression Theme:T2
E20	Regulation Theme:E18
M1	Speculation E14
