T1	Protein	p50
T3	Protein	p65
T9	Protein	tumor necrosis factor-alpha
T10	Protein	interleukin-1 beta
T11	Protein	interleukin-6
*	Equiv T1 T1
E1	Positive_regulation Theme:T1
E2	Positive_regulation Theme:T1
E3	Positive_regulation Theme:T3
E4	Positive_regulation Theme:T1
E5	Regulation Theme:E9
E6	Regulation Theme:E10
E7	Regulation Theme:E8
E8	Gene_expression Theme:T11
E9	Gene_expression Theme:T10
E10	Gene_expression Theme:T9
M1	Speculation E5
M2	Speculation E6
M3	Speculation E7
