T1	Protein	cdc-2
T2	Protein	cyclin E
T3	Protein	CD23
T4	Protein	cyclin D2
T5	Protein	CD40
T6	Protein	IL4
E1	Gene_expression Theme:T2
E2	Gene_expression Theme:T3
E3	Gene_expression Theme:T1
E4	Gene_expression Theme:T4
E5	Positive_regulation Theme:E1
E6	Positive_regulation Theme:E3
E7	Positive_regulation Theme:E4
E8	Positive_regulation Theme:E2
E9	Positive_regulation Theme:E16
E10	Positive_regulation Theme:E15
E11	Positive_regulation Theme:E13
E12	Positive_regulation Theme:E14
E13	Gene_expression Theme:T4
E14	Gene_expression Theme:T1
E15	Gene_expression Theme:T2
E16	Gene_expression Theme:T3
