T1	Protein	CREB
T2	Protein	cAMP response element binding protein
T4	Protein	activating transcription factor-1
T5	Protein	ATF-1
T6	Protein	CD2
T19	Protein	CD2 receptor
*	Equiv T4 T5
*	Equiv T1 T2
T33	Entity	serine 133
E1	Positive_regulation Theme:E2
E2	Phosphorylation Theme:T2
E3	Binding Theme:T6
E4	Phosphorylation Theme:T2
E5	Binding Theme:T6
E6	Binding Theme:T6
E7	Positive_regulation Theme:E8
E8	Phosphorylation Theme:T2
E9	Phosphorylation Theme:T2
E10	Positive_regulation Theme:E9
E11	Positive_regulation Theme:E9
E12	Binding Theme:T6
E13	Phosphorylation Site:T33 Theme:T2
E14	Regulation Cause:T6 Theme:T4
E15	Regulation Cause:T6 Theme:T2
