T1	Protein	IL-10
T4	Protein	tumor necrosis factor
T5	Protein	TNF
T9	Protein	IL-6
T10	Protein	IL-1ra
T13	Protein	IL-1beta
T19	Protein	CD16
T20	Protein	CD68
T21	Protein	CD14
*	Equiv T4 T5
E1	Positive_regulation Theme:E3
E2	Gene_expression Theme:T4
E3	Positive_regulation Theme:E2
E4	Positive_regulation Theme:E6
E5	Gene_expression Theme:T4
E6	Positive_regulation Theme:E5
E7	Positive_regulation Theme:E9
E8	Gene_expression Theme:T10
E9	Gene_expression Theme:T9
E10	Positive_regulation Theme:E8
E11	Positive_regulation Theme:E7
E12	Positive_regulation Theme:E13
E13	Localization Theme:T4
E14	Positive_regulation Theme:E13
M1	Negation E14
