T1	Protein	beta-catenin
T2	Protein	lymphoid enhancer factor 1
T7	Protein	LEF-1
T8	Protein	E-cadherin
T9	Protein	APC
T10	Protein	axin
T13	Protein	beta-Catenin
T18	Protein	VP16
T19	Entity	Nuclear
T24	Entity	nucleus
T35	Entity	nuclear
E1	Localization AtLoc:T19 Theme:T2
E2	Localization AtLoc:T19 Theme:T1
E3	Binding Theme:T1 Theme2:T2
E4	Positive_regulation Theme:E5
E5	Localization AtLoc:T24 Theme:T1
E6	Positive_regulation Theme:E4
E7	Localization Theme:T1 ToLoc:T24
E8	Binding Theme:T1
E9	Localization Theme:T1
E10	Negative_regulation Theme:E15
E11	Negative_regulation Theme:E17
E12	Negative_regulation Theme:E16
E13	Negative_regulation Theme:E14
E14	Binding Theme:T1 Theme2:T10
E15	Binding Theme:T1 Theme2:T7
E16	Binding Theme:T1 Theme2:T8
E17	Binding Theme:T1 Theme2:T9
E18	Localization AtLoc:T24 Theme:T1
E19	Localization AtLoc:T35 Theme:T13
E20	Localization AtLoc:T35 Theme:T7
E21	Localization Theme:T13 ToLoc:T24
E22	Localization Theme:T7 ToLoc:T24
E23	Positive_regulation Theme:T1
M1	Speculation E6
M2	Speculation E9
M3	Negation E13
