T1	Protein	IL-2
T3	Protein	OCT-1
T6	Protein	CD28
T9	Entity	promoter
E1	Binding Site:T9 Theme:T1
E2	Regulation Site:T9 Theme:T1
E3	Regulation Theme:E4
E4	Regulation Theme:E5
E5	Gene_expression Theme:T1
E6	Positive_regulation Theme:T3
E7	Positive_regulation Theme:T3
E8	Positive_regulation Cause:T1 Theme:T3
E9	Positive_regulation Theme:T3
E10	Positive_regulation Theme:T3
E11	Positive_regulation Theme:E12
E12	Gene_expression Theme:T1
M1	Speculation E3
M2	Negation E8
