T1	Protein	cyclooxygenase-2
T4	Protein	COX-2
*	Equiv T1 T4
E1	Negative_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Negative_regulation Theme:T1
E4	Positive_regulation Theme:E5
E5	Negative_regulation Theme:E6
E6	Gene_expression Theme:T1
E7	Negative_regulation Theme:E8
E8	Gene_expression Theme:T1
E9	Negative_regulation Theme:E10
E10	Gene_expression Theme:T1
E11	Gene_expression Theme:T1
M1	Negation E4
