T1	Protein	IFN regulating factor-1
T2	Protein	IRF-1
T3	Protein	CD4
T4	Protein	MIP-1alpha
T5	Protein	MIP-1beta
T6	Protein	IL-1RA
T7	Protein	IFN regulatory factor-1
T12	Protein	IFN-gamma
T14	Protein	STAT4
T21	Protein	IL-4
*	Equiv T1 T2 T2 T7
T39	Entity	promoter
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T2
E3	Positive_regulation Theme:T2
E4	Positive_regulation Theme:T5
E5	Positive_regulation Theme:T6
E6	Positive_regulation Theme:T4
E7	Regulation Theme:T2
E8	Positive_regulation Theme:T2
E9	Regulation Theme:T2
E10	Positive_regulation Cause:E11 Theme:E9
E11	Positive_regulation Theme:E12
E12	Gene_expression Theme:T12
E13	Positive_regulation Theme:T2
E14	Regulation Cause:T14 Theme:E15
E15	Regulation Theme:T2
E16	Binding Theme:T14 Site2:T39 Theme2:T2
E17	Positive_regulation Theme:T2
E18	Negative_regulation Cause:T21 Theme:E19
E19	Positive_regulation Theme:T2
E20	Positive_regulation Theme:T2
M1	Negation E10
M2	Negation E13
M3	Negation E17
M4	Negation E18
