T1	Protein	Bcl-2
T2	Protein	Raf-1
T3	Protein	MAPK kinase-1
T4	Protein	bcl-2
E1	Gene_expression Theme:T4
E2	Positive_regulation Theme:E1
E3	Gene_expression Theme:T1
E4	Positive_regulation Theme:E3
E5	Positive_regulation Theme:T3
E6	Positive_regulation Theme:E7
E7	Gene_expression Theme:T1
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T1
E10	Positive_regulation Theme:E11
E11	Gene_expression Theme:T4
E12	Regulation Cause:T3 Theme:T1
