T1	Protein	CD14
T2	Protein	c-myc
T3	Protein	c-fos
T4	Protein	c-jun
T5	Protein	transforming growth factor-beta 1
T6	Protein	TGF-beta 1
*	Equiv T5 T6
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Negative_regulation Theme:E4
E4	Gene_expression Theme:T2
E5	Positive_regulation Theme:E7
E6	Positive_regulation Theme:E8
E7	Gene_expression Theme:T3
E8	Gene_expression Theme:T4
E9	Regulation Theme:E12
E10	Regulation Theme:E14
E11	Regulation Theme:E13
E12	Gene_expression Theme:T4
E13	Gene_expression Theme:T2
E14	Gene_expression Theme:T3
M1	Negation E9
M2	Negation E10
M3	Negation E11
