T1	Protein	Bcl-x
T2	Protein	Bfl-1/A1
T3	Protein	CD40
T8	Protein	A1/Bfl-1
T11	Protein	Bfl-1
T14	Protein	Fas
E1	Positive_regulation Theme:T2
E2	Positive_regulation Theme:T1
E3	Positive_regulation Theme:T3
E4	Regulation Cause:T3 Theme:T1
E5	Positive_regulation Cause:T3 Theme:T8
E6	Negative_regulation Theme:E9
E7	Negative_regulation Theme:E8
E8	Positive_regulation Cause:T3 Theme:T11
E9	Positive_regulation Cause:T3 Theme:T1
E10	Gene_expression Theme:T1
