T1	Protein	PML-RAR
T2	Protein	retinoic acid receptor type alpha
T3	Protein	RAR alpha
T5	Protein	granulocyte colony-stimulating factor
T6	Protein	G-CSF
T7	Protein	leukocyte alkaline phosphatase
T8	Protein	CD11b
T9	Protein	CD33
T10	Protein	G-CSF receptor
T11	Protein	LAP
T12	Protein	RAR beta
T13	Protein	RAR gamma
*	Equiv T2 T3
*	Equiv T5 T6
E1	Gene_expression Theme:T1
E2	Positive_regulation Theme:T1
E3	Regulation Theme:E8
E4	Regulation Theme:E9
E5	Regulation Theme:E7
E6	Regulation Theme:E10
E7	Gene_expression Theme:T7
E8	Gene_expression Theme:T10
E9	Gene_expression Theme:T9
E10	Gene_expression Theme:T8
E11	Positive_regulation Theme:T11
E12	Gene_expression Theme:T1
E13	Binding Theme:T1
E14	Binding Theme:T2
E15	Gene_expression Theme:T1
