T1	Protein	HSF1
T3	Protein	IL1B
T4	Protein	c- fos
T9	Protein	TNF-alpha
T10	Protein	IL-1beta
T11	Protein	IL-6
T12	Protein	IL-8
T13	Protein	IL-10
T14	Protein	ICAM-1
T18	Protein	HSP70B
T19	Protein	HSP70
T27	Entity	promoter
E1	Positive_regulation Theme:E2
E2	Binding Theme:T1
E3	Positive_regulation Cause:T1 Theme:T3
E4	Positive_regulation Cause:T1 Theme:T4
E5	Negative_regulation Cause:T1 Theme:T3
E6	Negative_regulation Cause:T1 Theme:T4
E7	Negative_regulation Site:T27 Theme:T3
E8	Negative_regulation Theme:E12
E9	Negative_regulation Theme:E11
E10	Negative_regulation Theme:E13
E11	Positive_regulation Theme:E16
E12	Positive_regulation Theme:E14
E13	Positive_regulation Theme:E15
E14	Gene_expression Theme:T3
E15	Gene_expression Theme:T4
E16	Gene_expression Theme:T1
E17	Positive_regulation Theme:T1
E18	Negative_regulation Theme:E30
E19	Negative_regulation Theme:E34
E20	Negative_regulation Theme:E31
E21	Negative_regulation Theme:E32
E22	Negative_regulation Theme:E33
E23	Negative_regulation Theme:E35
E24	Gene_expression Theme:T12
E25	Gene_expression Theme:T11
E26	Gene_expression Theme:T14
E27	Gene_expression Theme:T13
E28	Gene_expression Theme:T9
E29	Gene_expression Theme:T10
E30	Positive_regulation Theme:E29
E31	Positive_regulation Theme:E24
E32	Positive_regulation Theme:E25
E33	Positive_regulation Theme:E26
E34	Positive_regulation Theme:E27
E35	Positive_regulation Theme:E28
E36	Negative_regulation Site:T27 Theme:T3
E37	Regulation Site:T27 Theme:T3
E38	Binding Site:T27 Theme:T3 Theme2:T1
E39	Positive_regulation Site:T27 Theme:T18
E40	Positive_regulation Site:T27 Theme:T18
E41	Positive_regulation Theme:T19
E42	Positive_regulation Theme:E43
E43	Binding Theme:T1
M1	Negation E37
M2	Negation E39
