T1	Protein	c-Fos
T2	Protein	v-Fos
T3	Protein	c-Jun
E1	Positive_regulation Theme:E4
E2	Positive_regulation Theme:E3
E3	Protein_catabolism Theme:T2
E4	Protein_catabolism Theme:T1
E5	Binding Theme:T1 Theme2:T3
E6	Positive_regulation Theme:E5
E7	Protein_catabolism Theme:T1
E8	Regulation Theme:E7
E9	Negative_regulation Theme:T1
E10	Positive_regulation Cause:E11 Theme:E9
E11	Binding Theme:T1 Theme2:T3
E12	Phosphorylation Theme:T3
E13	Positive_regulation Cause:T3 Theme:E14
E14	Protein_catabolism Theme:T1
E15	Protein_catabolism Theme:T1
E16	Positive_regulation Theme:E15
E17	Positive_regulation Theme:T2
E18	Protein_catabolism Theme:T2
E19	Binding Theme:T2 Theme2:T3
M1	Negation E2
M2	Negation E13
M3	Negation E15
M4	Negation E17
