T1	Protein	interferon-gamma
T2	Protein	IgG Fc receptor type IC
T4	Protein	IgG Fc receptor type I
T5	Protein	Fc gamma RI
T7	Protein	IFN-gamma
T14	Protein	Fc gamma RIC
T15	Protein	CAT
T20	Protein	STAT1 alpha
*	Equiv T4 T5
*	Equiv T1 T7
E1	Positive_regulation Theme:E2
E2	Regulation Cause:T1 Theme:T2
E3	Gene_expression Theme:T4
E4	Positive_regulation Theme:E3
E5	Positive_regulation Theme:T4
E6	Positive_regulation Theme:E7
E7	Positive_regulation Theme:E8
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T4
E10	Transcription Theme:T4
E11	Positive_regulation Cause:T1 Theme:E10
E12	Binding Theme:T20
E13	Positive_regulation Theme:E12
E14	Regulation Cause:T1 Theme:T14
E15	Regulation Cause:E16 Theme:E14
E16	Binding Theme:T20
