T1	Protein	YY1
T2	Protein	Oct1
T3	Protein	IL-5
T8	Protein	hIL-5
*	Equiv T3 T8
T31	Entity	promoter
E1	Binding Theme:T2
E2	Binding Theme:T1
E3	Negative_regulation Theme:E4
E4	Gene_expression Theme:T8
E5	Positive_regulation Theme:T8
E6	Gene_expression Theme:T8
E7	Regulation Theme:E6
E8	Regulation Theme:E9
E9	Negative_regulation Theme:E10
E10	Transcription Theme:T8
E11	Regulation Site:T31 Theme:T8
E12	Regulation Theme:E13
E13	Gene_expression Theme:T8
E14	Negative_regulation Site:T31 Theme:T8
E15	Binding Theme:T2
E16	Binding Theme:T1
E17	Negative_regulation Theme:E20
E18	Negative_regulation Theme:E19
E19	Binding Theme:T2
E20	Binding Theme:T1
E21	Positive_regulation Site:T31 Theme:T8
E22	Binding Theme:T1 Site2:T31 Theme2:T8
E23	Binding Theme:T2 Site2:T31 Theme2:T8
E24	Binding Site:T31 Theme:T8
E25	Regulation Cause:E23 Theme:E28
E26	Regulation Cause:E24 Theme:E28
E27	Regulation Cause:E22 Theme:E28
E28	Negative_regulation Theme:E29
E29	Transcription Theme:T8
M1	Speculation E8
