T1	Protein	MZF-1
T2	Protein	CD34
T7	Protein	GAL4
T8	Protein	chloramphenicol acetyl transferase
T9	Protein	CAT
T10	Protein	thymidine kinase
*	Equiv T8 T9
T32	Entity	promoter
T46	Entity	consensus binding sites
E1	Regulation Cause:T1 Site:T32 Theme:T2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E2
E4	Regulation CSite:T32 Cause:T10 Theme:T8
E5	Negative_regulation Cause:T1 Theme:E6
E6	Gene_expression Theme:T8
E7	Positive_regulation Cause:T7 Theme:E5
E8	Positive_regulation Cause:T1 Theme:E9
E9	Gene_expression Theme:T8
E10	Gene_expression Theme:T2
E11	Regulation Cause:T1 Site:T32 Theme:T2
E12	Binding Theme:T1 Site2:T46 Theme2:T2
E13	Positive_regulation Theme:E14
E14	Gene_expression Theme:T2
E15	Positive_regulation Theme:E13
E16	Regulation Cause:T1 Site:T32 Theme:T2
E17	Regulation Theme:E16
M1	Speculation E11
