T1	Protein	IL-2
T2	Protein	IL-7
T3	Protein	interleukin (IL)-2
T5	Protein	STAT5A
T6	Protein	STAT5B
T12	Protein	L-7
T29	Entity	nucleus
T32	Entity	tyrosine
E1	Positive_regulation Cause:T1 Theme:E3
E2	Positive_regulation Cause:T2 Theme:E3
E3	Binding Theme:T5 Theme2:T6
E4	Binding Theme:T6
E5	Binding Theme:T5
E6	Localization Theme:T6 ToLoc:T29
E7	Localization Theme:T5 ToLoc:T29
E8	Positive_regulation Cause:T1 Theme:E6
E9	Positive_regulation Cause:T1 Theme:E7
E10	Positive_regulation Cause:T1 Theme:E14
E11	Positive_regulation Cause:T2 Theme:E14
E12	Positive_regulation Cause:T2 Theme:E15
E13	Positive_regulation Cause:T1 Theme:E15
E14	Phosphorylation Site:T32 Theme:T5
E15	Phosphorylation Site:T32 Theme:T6
E16	Positive_regulation Cause:T1 Theme:E21
E17	Positive_regulation Cause:T1 Theme:E20
E18	Positive_regulation Cause:T2 Theme:E20
E19	Positive_regulation Cause:T2 Theme:E21
E20	Binding Theme:T5
E21	Binding Theme:T6
E22	Binding Theme:T5 Theme2:T6
E23	Binding Theme:T5
E24	Binding Theme:T6
