T1	Protein	Oct-2
T2	Protein	Bob1
T3	Protein	BLR1
T5	Protein	blr1
T8	Protein	p50
T9	Protein	p52
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T3
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T5
E5	Gene_expression Theme:T3
E6	Negative_regulation Theme:E5
E7	Gene_expression Theme:T3
E8	Regulation Theme:E7
E9	Regulation Cause:T1 Theme:T3
E10	Regulation Theme:T3
E11	Regulation Cause:T2 Theme:T3
E12	Gene_expression Theme:T2
E13	Gene_expression Theme:T1
M1	Negation E5
M2	Negation E8
M3	Negation E12
M4	Negation E13
