T1	Protein	EBF
T2	Protein	E47
T3	Protein	Early B cell factor
T10	Protein	lambda5
T11	Protein	VpreB
*	Equiv T1 T3
E1	Gene_expression Theme:T3
E2	Gene_expression Theme:T2
E3	Positive_regulation Theme:E2
E4	Positive_regulation Theme:E1
E5	Gene_expression Theme:T2
E6	Gene_expression Theme:T3
E7	Positive_regulation Cause:T3 Theme:E11
E8	Positive_regulation Cause:T2 Theme:E12
E9	Positive_regulation Cause:T2 Theme:E11
E10	Positive_regulation Cause:T3 Theme:E12
E11	Gene_expression Theme:T10
E12	Gene_expression Theme:T11
E13	Regulation Cause:T3 Theme:T10
E14	Regulation Cause:T2 Theme:T10
M1	Negation E5
M2	Negation E6
