T1	Protein	IL-2
T2	Protein	c-fos
T3	Protein	PHA
T4	Protein	CD2
T5	Protein	lymphocyte function-associated Ag-3
T10	Protein	c-jun
T23	Protein	c-Jun
T24	Protein	c-Fos
T53	Entity	proximal AP-1 site
E1	Positive_regulation Theme:E2
E2	Transcription Theme:T1
E3	Binding Theme:T5
E4	Positive_regulation Theme:E7
E5	Positive_regulation Theme:E6
E6	Binding Theme:T4 Theme2:T5
E7	Binding Theme:T4
E8	Positive_regulation Theme:E9
E9	Gene_expression Theme:T1
E10	Positive_regulation Cause:E12 Theme:E11
E11	Positive_regulation Theme:T1
E12	Positive_regulation Theme:E13
E13	Transcription Theme:T1
E14	Regulation Theme:T10
E15	Regulation Theme:T2
E16	Regulation Cause:T2 Theme:E18
E17	Regulation Cause:T10 Theme:E18
E18	Transcription Theme:T1
E19	Gene_expression Theme:T10
E20	Regulation Theme:T10
E21	Transcription Theme:T2
E22	Positive_regulation Theme:T2
E23	Positive_regulation Theme:T2
E24	Positive_regulation Theme:T2
E25	Binding Site:T53 Theme:T1
E26	Regulation Theme:E27
E27	Regulation Theme:T1
E28	Regulation Cause:E30 Theme:E29
E29	Positive_regulation Theme:E30
E30	Transcription Theme:T1
M1	Speculation E14
M2	Speculation E15
M3	Negation E20
M4	Negation E21
M5	Negation E23
