T1	Protein	OBF-1
T2	Protein	Oct-1
T3	Protein	Oct-2
T4	Protein	Oct-binding factor 1
T11	Protein	Oct-4
T12	Protein	Oct-6
*	Equiv T1 T4
T20	Entity	POU domains
E1	Binding Theme:T4
E2	Binding Theme:T4 Theme2:T3
E3	Binding Theme:T4 Theme2:T2
E4	Binding Theme:T4
E5	Binding Theme:T4 Site2:T20 Theme2:T2
E6	Binding Theme:T4 Site2:T20 Theme2:T3
E7	Binding Theme:T4 Site2:T20 Theme2:T12
E8	Binding Theme:T4 Site2:T20 Theme2:T11
E9	Transcription Theme:T4
E10	Gene_expression Theme:T4
M1	Negation E4
M2	Negation E7
M3	Negation E8
M4	Negation E9
