T1	Protein	EKLF
T2	Protein	GATA-1
T3	Protein	GATA-2
T4	Protein	p45 NF-E2
T5	Protein	PU.1
T6	Protein	SCL
T7	Protein	Tal1
T8	Protein	CD34
T10	Protein	c-kit
T13	Protein	CD36
T14	Protein	erythropoietin receptor
T15	Protein	EpoR
T20	Protein	glyocophorin A
T21	Protein	GPA
T34	Protein	CD38
*	Equiv T14 T15
*	Equiv T20 T21
*	Equiv T6 T7
E1	Gene_expression Theme:T1
E2	Gene_expression Theme:T4
E3	Gene_expression Theme:T5
E4	Gene_expression Theme:T3
E5	Gene_expression Theme:T7
E6	Gene_expression Theme:T2
E7	Gene_expression Theme:T8
E8	Gene_expression Theme:T5
E9	Gene_expression Theme:T10
E10	Gene_expression Theme:T3
E11	Gene_expression Theme:T7
E12	Gene_expression Theme:T14
E13	Gene_expression Theme:T2
E14	Gene_expression Theme:T1
E15	Gene_expression Theme:T13
E16	Gene_expression Theme:T20
E17	Positive_regulation Theme:T13
E18	Positive_regulation Theme:T1
E19	Positive_regulation Theme:T7
E20	Gene_expression Theme:T2
E21	Gene_expression Theme:T14
E22	Positive_regulation Theme:T20
E23	Gene_expression Theme:T5
E24	Gene_expression Theme:T10
E25	Gene_expression Theme:T8
E26	Gene_expression Theme:T3
E27	Transcription Theme:T8
E28	Negative_regulation Theme:T8
M1	Speculation E1
M2	Speculation E2
M3	Speculation E3
M4	Speculation E4
M5	Speculation E5
M6	Speculation E6
M7	Negation E11
M8	Negation E12
M9	Negation E13
M10	Negation E14
M11	Negation E15
M12	Negation E16
M13	Negation E23
M14	Negation E24
M15	Negation E25
M16	Negation E26
