T1	Protein	interleukin-1 beta
T3	Protein	IL-1 beta
T5	Protein	vitamin D receptor
*	Equiv T1 T3
E1	Positive_regulation Theme:E2
E2	Positive_regulation Theme:E3
E3	Transcription Theme:T1
E4	Positive_regulation Theme:T1
E5	Positive_regulation Theme:T1
E6	Regulation Theme:E5
E7	Regulation Theme:E4
E8	Gene_expression Theme:T5
E9	Positive_regulation Theme:T1
E10	Positive_regulation Theme:T1
E11	Regulation Theme:E13
E12	Transcription Theme:T1
E13	Positive_regulation Theme:E12
E14	Positive_regulation Theme:T1
M1	Speculation E4
M2	Speculation E5
M3	Speculation E6
M4	Speculation E7
