T1	Protein	interleukin 2
T2	Protein	IL-2
T3	Protein	c-Jun
T5	Protein	NFATp
T8	Protein	c-Jun NH2-terminal kinase
T9	Protein	JNK
*	Equiv T1 T2
*	Equiv T8 T9
E1	Negative_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T3
E5	Regulation Theme:T5
E6	Positive_regulation Theme:E7
E7	Localization Theme:T5
E8	Positive_regulation Cause:E6 Theme:E9
E9	Localization Theme:T5
E10	Phosphorylation Theme:T5
E11	Positive_regulation Cause:T8 Theme:E10
