T1	Protein	interleukin 2
T3	Protein	IL2
T7	Protein	TGF beta 1
T8	Protein	TGF beta 2
*	Equiv T1 T3
T11	Entity	enhancer
E1	Negative_regulation Theme:E2
E2	Positive_regulation Site:T11 Theme:T1
E3	Negative_regulation Cause:E5 Theme:E4
E4	Gene_expression Theme:T1
E5	Negative_regulation Theme:E6
E6	Positive_regulation Theme:T1
E7	Negative_regulation Theme:E8
E8	Transcription Theme:T1
E9	Localization Theme:T7
E10	Localization Theme:T8
M1	Speculation E7
