T1	Protein	interleukin-2 receptor-alpha
T2	Protein	IL-2Ralpha
T8	Protein	interferon-gamma
T9	Protein	IFN-gamma
T11	Protein	p50
T12	Protein	p65
*	Equiv T1 T2
*	Equiv T8 T9
T27	Entity	promoter
E1	Positive_regulation Theme:T1
E2	Negative_regulation Theme:E1
E3	Gene_expression Theme:T1
E4	Positive_regulation Theme:T1
E5	Gene_expression Theme:T1
E6	Positive_regulation Theme:E5
E7	Gene_expression Theme:T1
E8	Positive_regulation Theme:E7
E9	Positive_regulation Theme:E10
E10	Gene_expression Theme:T1
E11	Positive_regulation Cause:T8 Theme:E10
E12	Positive_regulation Site:T27 Theme:T1
E13	Gene_expression Theme:T1
M1	Speculation E3
M2	Speculation E4
