T1	Protein	delta
T2	Protein	beta
T11	Protein	CAT
T13	Protein	beta globin
T23	Protein	delta globi
T24	Protein	BP1
T25	Protein	BP2
T27	Protein	DNase I
T28	Protein	delta-globin
T29	Protein	GATA-1
T35	Entity	promoter
T43	Entity	upstream promoter region
E1	Regulation Theme:E4
E2	Regulation Theme:E3
E3	Negative_regulation Theme:T2
E4	Negative_regulation Theme:T1
E5	Positive_regulation CSite:T35 Cause:T1 Theme:T11
E6	Positive_regulation CSite:T35 Cause:T13 Theme:T11
E7	Positive_regulation Site:T35 Theme:T13
E8	Negative_regulation Theme:E9
E9	Gene_expression Theme:T11
E10	Positive_regulation Site:T35 Theme:T13
E11	Positive_regulation CSite:T43 Cause:T13 Theme:E12
E12	Negative_regulation Theme:T13
E13	Regulation Cause:E11 Theme:E14
E14	Gene_expression Theme:T13
M1	Negation E6
