T1	Protein	CR1
T2	Protein	CD35
T3	Protein	CD11b
T4	Protein	CD18
T5	Protein	p50
T6	Protein	p65
T7	Protein	TNF-alpha
T17	Protein	p24
*	Equiv T1 T1 T2 T2
T29	Entity	nuclear
E1	Positive_regulation Theme:T1
E2	Positive_regulation Theme:T3
E3	Positive_regulation Theme:T4
E4	Positive_regulation Cause:E2 Theme:E10
E5	Positive_regulation Cause:E3 Theme:E10
E6	Positive_regulation Cause:E1 Theme:E11
E7	Positive_regulation Cause:E1 Theme:E10
E8	Positive_regulation Cause:E3 Theme:E11
E9	Positive_regulation Cause:E2 Theme:E11
E10	Localization Theme:T6 ToLoc:T29
E11	Localization Theme:T5 ToLoc:T29
E12	Positive_regulation Theme:E16
E13	Positive_regulation Theme:E17
E14	Positive_regulation Cause:T7 Theme:E17
E15	Positive_regulation Cause:T7 Theme:E16
E16	Localization Theme:T5 ToLoc:T29
E17	Localization Theme:T6 ToLoc:T29
E18	Binding Theme:T6
E19	Binding Theme:T5
E20	Positive_regulation Theme:T1
E21	Positive_regulation Theme:T3
E22	Positive_regulation Theme:T4
E23	Positive_regulation Theme:T1
E24	Positive_regulation Theme:T17
E25	Positive_regulation Cause:E23 Theme:T17
E26	Positive_regulation Theme:T1
E27	Positive_regulation Theme:E32
E28	Positive_regulation Cause:E26 Theme:E31
E29	Positive_regulation Theme:E31
E30	Positive_regulation Cause:E26 Theme:E32
E31	Localization Theme:T6 ToLoc:T29
E32	Localization Theme:T5 ToLoc:T29
E33	Localization Theme:T5
E34	Localization Theme:T6
E35	Positive_regulation Cause:E39 Theme:E34
E36	Positive_regulation Cause:E39 Theme:E33
E37	Positive_regulation Theme:E33
E38	Positive_regulation Theme:E34
E39	Positive_regulation Theme:T1
E40	Localization Theme:T5
E41	Localization Theme:T6
E42	Positive_regulation Theme:E40
E43	Positive_regulation Theme:E41
E44	Positive_regulation Cause:T7 Theme:E49
E45	Positive_regulation Cause:T7 Theme:E48
E46	Localization Theme:T5
E47	Localization Theme:T6
E48	Positive_regulation Theme:T5
E49	Positive_regulation Theme:T6
M1	Negation E44
M2	Negation E45
