T1	Protein	monocyte chemotactic protein-1
T2	Protein	intercellular adhesion molecule-1
T4	Protein	MCP-1
T6	Protein	ICAM-1
*	Equiv T2 T6
*	Equiv T1 T4
T24	Entity	surface
E1	Positive_regulation Theme:E3
E2	Positive_regulation Theme:E4
E3	Localization Theme:T1
E4	Gene_expression Theme:T2
E5	Regulation Theme:E7
E6	Regulation Theme:E8
E7	Localization Theme:T1
E8	Gene_expression Theme:T2
E9	Localization Theme:T1
E10	Localization AtLoc:T24 Theme:T2
E11	Localization Theme:T1
E12	Localization AtLoc:T24 Theme:T2
E13	Positive_regulation Theme:E12
E14	Positive_regulation Theme:E11
E15	Negative_regulation Theme:E18
E16	Negative_regulation Theme:E17
E17	Localization Theme:T1
E18	Localization AtLoc:T24 Theme:T2
E19	Positive_regulation Theme:T1
E20	Positive_regulation Theme:T2
E21	Regulation Theme:E20
E22	Regulation Theme:E19
M1	Speculation E9
M2	Speculation E10
M3	Negation E15
M4	Negation E16
