T1	Protein	ecto-5'-nucleotidase
T3	Protein	5'-NT
T4	Protein	CAT
T5	Protein	ecto-5'-NT
T6	Protein	DNase I
T7	Protein	Sp1
T10	Protein	NRE-2a
T11	Protein	TCF-1
T12	Protein	LEF-1
T15	Protein	ATF-1
T16	Protein	ATF-2
*	Equiv T11 T12
T19	Entity	promoter
E1	Regulation Site:T19 Theme:T1
E2	Regulation Theme:E3
E3	Positive_regulation Theme:E4
E4	Negative_regulation Site:T19 Theme:T1
E5	Transcription Theme:T5
E6	Binding Theme:T15
E7	Binding Theme:T16
