T1	Protein	G0/G1 switch gene 2
T2	Protein	G0S2
T3	Protein	interleukin-2
T4	Protein	IL2
T6	Protein	G0/G1 switch gene
T10	Protein	G0S
*	Equiv T1 T2 T2 T6
*	Equiv T3 T4
E1	Negative_regulation Theme:E2
E2	Transcription Theme:T2
E3	Transcription Theme:T2
E4	Positive_regulation Theme:E5
E5	Transcription Theme:T2
E6	Positive_regulation Theme:T10
E7	Positive_regulation Theme:T2
E8	Negative_regulation Theme:E7
E9	Gene_expression Theme:T2
E10	Negative_regulation Theme:E11
E11	Gene_expression Theme:T2
M1	Speculation E3
