T1	Protein	VCAM-1
T2	Protein	IFN-gamma
T3	Protein	iNO synthase
T4	Protein	iNOS
T10	Protein	RelA
T11	Protein	p65
*	Equiv T3 T4
*	Equiv T10 T11
E1	Gene_expression Theme:T1
E2	Positive_regulation Cause:T2 Theme:E1
E3	Positive_regulation Theme:E1
E4	Negative_regulation Theme:T4
E5	Positive_regulation Cause:E4 Theme:E8
E6	Positive_regulation Cause:E4 Theme:E7
E7	Gene_expression Theme:T4
E8	Gene_expression Theme:T1
E9	Negative_regulation Theme:E10
E10	Transcription Theme:T1
E11	Positive_regulation Theme:E9
E12	Negative_regulation Theme:E13
E13	Gene_expression Theme:T4
