T1	Protein	interleukin-2 receptor alpha-chain
T2	Protein	Elf-1
T3	Protein	HMG-I(Y)
T4	Protein	interleukin 2 receptor alpha-chain
T5	Protein	IL-2R alpha
T13	Protein	HMG-I
T14	Protein	p50
T15	Protein	c-Rel
*	Equiv T4 T5
T27	Entity	promoter
E1	Regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Binding Theme:T2
E4	Binding Theme:T3
E5	Gene_expression Theme:T4
E6	Positive_regulation Theme:E5
E7	Binding Theme:T3
E8	Binding Theme:T2
E9	Gene_expression Theme:T2
E10	Transcription Theme:T4
E11	Positive_regulation CSite:T27 Cause:T4 Theme:E10
E12	Negative_regulation Theme:E11
E13	Gene_expression Theme:T2
E14	Gene_expression Theme:T3
E15	Binding Theme:T2 Theme2:T15
E16	Binding Theme:T2 Theme2:T14
E17	Binding Theme:T2 Theme2:T13
E18	Regulation Theme:E19
E19	Gene_expression Theme:T4
