T1	Protein	interleukin-8
T2	Protein	IL-8
T7	Protein	macrophage chemotactic protein-1
T10	Protein	myeloperoxidase
T11	Protein	IP-10
E1	Positive_regulation Theme:E2
E2	Gene_expression Theme:T1
E3	Positive_regulation Theme:E4
E4	Localization Theme:T2
E5	Positive_regulation Theme:T2
E6	Positive_regulation Theme:T2
E7	Positive_regulation Theme:E8
E8	Transcription Theme:T2
E9	Positive_regulation Theme:T7
E10	Positive_regulation Theme:T2
E11	Positive_regulation Theme:T2
E12	Positive_regulation Theme:T11
