T1	Protein	zeta 2 globin
T2	Protein	alpha globin
T10	Protein	GATA-1
T16	Entity	promoter
E1	Positive_regulation Site:T16 Theme:T1
E2	Positive_regulation Site:T16 Theme:T1
E3	Positive_regulation Theme:E4
E4	Gene_expression Theme:T1
E5	Positive_regulation Theme:E6
E6	Positive_regulation Theme:E7
E7	Regulation Site:T16 Theme:T1
E8	Regulation Theme:E9
E9	Positive_regulation Site:T16 Theme:T1
E10	Transcription Theme:T1
E11	Transcription Theme:T2
E12	Positive_regulation Theme:E10
E13	Positive_regulation Theme:E11
E14	Positive_regulation Theme:E12
E15	Positive_regulation Theme:E13
M1	Negation E3
