T1	Protein	heparin-binding epidermal growth factor-like growth factor
T3	Protein	HB-EGF
*	Equiv T1 T3
E1	Positive_regulation Theme:E2
E2	Transcription Theme:T1
E3	Positive_regulation Theme:T1
E4	Positive_regulation Theme:T1
E5	Positive_regulation Theme:E4
E6	Negative_regulation Theme:E7
E7	Positive_regulation Theme:T1
E8	Regulation Theme:E9
E9	Positive_regulation Theme:T1
E10	Negative_regulation Theme:E4
E11	Negative_regulation Theme:E4
E12	Negative_regulation Theme:E13
E13	Positive_regulation Theme:T1
E14	Positive_regulation Theme:E15
E15	Gene_expression Theme:T1
E16	Positive_regulation Theme:E14
M1	Speculation E5
M2	Negation E8
M3	Negation E11
