T1	Protein	myeloid cell nuclear differentiation antigen
T2	Protein	Sp1
T3	Protein	c-Myb
T4	Protein	PU.1
T5	Protein	myeloid nuclear differentiation antigen
T6	Protein	MNDA
*	Equiv T5 T6
E1	Regulation Cause:T2 Theme:E4
E2	Regulation Cause:T4 Theme:E4
E3	Regulation Cause:T3 Theme:E4
E4	Gene_expression Theme:T1
E5	Gene_expression Theme:T5
E6	Gene_expression Theme:T5
E7	Positive_regulation Theme:T5
E8	Gene_expression Theme:T5
E9	Gene_expression Theme:T5
E10	Gene_expression Theme:T5
E11	Positive_regulation Theme:T5
E12	Negative_regulation Theme:E13
E13	Positive_regulation Theme:T5
E14	Regulation Theme:E13
E15	Binding Theme:T2
E16	Regulation Theme:E18
E17	Positive_regulation Theme:E18
E18	Gene_expression Theme:T5
M1	Negation E2
M2	Negation E3
M3	Speculation E7
M4	Negation E9
M5	Negation E14
