T1	Protein	I kappa B alpha
T3	Protein	Tax
E1	Phosphorylation Theme:T1
E2	Protein_catabolism Theme:T1
E3	Positive_regulation Cause:T3 Theme:E2
E4	Positive_regulation Cause:T3 Theme:E1
E5	Positive_regulation Theme:E2
E6	Positive_regulation Theme:E1
E7	Negative_regulation Cause:T1 Theme:E10
E8	Negative_regulation Cause:T1 Theme:E9
E9	Positive_regulation Theme:E11
E10	Positive_regulation Theme:E12
E11	Phosphorylation Theme:T1
E12	Protein_catabolism Theme:T1
E13	Phosphorylation Theme:T1
E14	Protein_catabolism Theme:T1
E15	Regulation Theme:T1
E16	Positive_regulation Theme:E15
