T1	Protein	interleukin 2
T3	Protein	IL-2
T4	Protein	interferon-gamma
T5	Protein	IFN-gamma
T11	Protein	chloramphenicol acetyltransferase
T12	Protein	CAT
T15	Protein	NFAT-1
T16	Protein	NFIL-2A
*	Equiv T11 T12
*	Equiv T1 T3
*	Equiv T4 T5
E1	Positive_regulation Theme:E2
E2	Transcription Theme:T1
E3	Positive_regulation Theme:E6
E4	Positive_regulation Theme:E5
E5	Gene_expression Theme:T1
E6	Gene_expression Theme:T4
E7	Positive_regulation Theme:E10
E8	Positive_regulation Theme:E9
E9	Regulation Theme:T1
E10	Regulation Theme:T1
E11	Gene_expression Theme:T4
E12	Negative_regulation Theme:E11
E13	Regulation Theme:T4
E14	Positive_regulation Theme:T4
E15	Positive_regulation Theme:E16
E16	Gene_expression Theme:T1
E17	Positive_regulation Theme:T15
E18	Regulation Theme:T16
E19	Negative_regulation Theme:E20
E20	Gene_expression Theme:T4
E21	Positive_regulation Cause:E24 Theme:E23
E22	Positive_regulation Cause:E25 Theme:E23
E23	Gene_expression Theme:T1
E24	Regulation Theme:T15
E25	Positive_regulation Cause:T1 Theme:E26
E26	Transcription Theme:T1
M1	Negation E13
M2	Negation E18
