T1	Protein	MLH1
T3	Protein	E-cadherin
T4	Protein	p16
T13	Entity	promoter
T15	Entity	5' CpG island
E1	DNA_methylation Site:T13 Theme:T1
E2	DNA_methylation Site:T15 Theme:T1
M1	Speculation E2
E3	DNA_methylation Site:T15 Theme:T3
M2	Speculation E3
E4	DNA_methylation Site:T15 Theme:T4
M3	Speculation E4
E5	DNA_methylation Theme:T1
E6	DNA_methylation Theme:T3
E7	DNA_methylation Theme:T4
E8	DNA_methylation Theme:T1
E9	DNA_methylation Theme:T1
E10	DNA_methylation Theme:T3
E11	DNA_methylation Theme:T4
E12	DNA_methylation Theme:T1
