T1	Protein	Bre1
T2	Protein	large 1
T3	Protein	Lge1
T4	Protein	H2B
T5	Protein	histone H2B
T7	Protein	Large 1
T8	Protein	Rad6
T11	Protein	ubiquitin
T12	Protein	Ubp8
T16	Protein	H3
*	Equiv T2 T3 T7
T30	Entity	lysine 123
T32	Entity	lysines 4
T33	Entity	79
E1	Catalysis Cause:T2 Theme:E2
E2	Ubiquitination Theme:T4
E3	Ubiquitination Theme:T5
E4	Deubiquitination Theme:T5
E5	Ubiquitination Site:T30 Theme:T5
E6	Methylation Site:T32 Theme:T16
E7	Methylation Site:T33 Theme:T16
