T1	Protein	Histone
T2	Protein	MFA2
T3	Protein	histone
T5	Protein	histone H3
T6	Protein	H4
T9	Protein	histone H4
T10	Protein	Gcn5p
T14	Protein	Swi2p
T18	Protein	Rad4p
T19	Protein	Rad14p
E1	Acetylation Theme:T1
E2	Acetylation Theme:T3
E3	Acetylation Theme:T5
E4	Acetylation Theme:T6
E5	Acetylation Theme:T3
E6	Acetylation Contextgene:T2 Theme:T5
E7	Acetylation Theme:T9
M1	Negation E7
E8	Catalysis Cause:T10 Theme:E9
E9	Acetylation Contextgene:T2 Theme:T5
