T1	Protein	hypoxia-inducible factor (HIF) asparaginyl hydroxylase
T2	Protein	factor inhibiting HIF
T3	Protein	FIH
T4	Protein	HIF asparaginyl hydroxylase
T8	Protein	p105
T9	Protein	NFKB1
T10	Protein	IkappaBalpha
*	Equiv T1 T2 T3 T4
*	Equiv T8 T9
T16	Entity	Asn residues
E1	Hydroxylation Site:T16 Theme:T8
E2	Catalysis Cause:T1 Theme:E1
E3	Hydroxylation Site:T16 Theme:T10
E4	Catalysis Cause:T1 Theme:E3
