T1	Protein	thymine DNA glycosylase
T2	Protein	Thymine DNA glycosylase
T3	Protein	TDG
T4	Protein	protein kinase C alpha
T5	Protein	PKCalpha
T7	Protein	CREB-binding protein
T8	Protein	CBP
T9	Protein	p300
*	Equiv T2 T3
*	Equiv T4 T5
*	Equiv T7 T8
T19	Entity	serine residues
T20	Entity	lysines
T25	Entity	amino-terminal region
E1	Phosphorylation Site:T19 Theme:T2
E2	Acetylation Site:T20 Theme:T2
E3	Acetylation Theme:T2
E4	Phosphorylation Theme:T2
E5	Acetylation Site:T25 Theme:T2
E6	Phosphorylation Theme:T2
E7	Acetylation Theme:T2
