T1	Protein	Histone H4
T3	Protein	H4
T8	Entity	lysine
T10	Entity	lysines 5
T11	Entity	8
T12	Entity	12
T13	Entity	16
T18	Entity	lysine 12
T20	Entity	lysine 16
E1	Acetylation Site:T8 Theme:T1
E2	Acetylation Site:T10 Theme:T1
E3	Acetylation Site:T11 Theme:T1
E4	Acetylation Site:T12 Theme:T1
E5	Acetylation Site:T13 Theme:T1
E6	Acetylation Site:T10 Theme:T3
E7	Acetylation Site:T11 Theme:T3
E8	Acetylation Site:T18 Theme:T3
E9	Acetylation Site:T20 Theme:T3
E10	Acetylation Theme:T3
