T1	Protein	histone H4
T3	Protein	H4
T8	Protein	PR-Set7
T9	Protein	histone
T12	Entity	lysine 20
T16	Entity	K20
E1	Methylation Site:T12 Theme:T1
E2	Methylation Site:T12 Theme:T1
E3	Methylation Site:T16 Theme:T3
E4	Methylation Theme:T3
E5	Methylation Site:T16 Theme:T3
E6	Methylation Theme:T3
E7	Acetylation Theme:T3
E8	Methylation Site:T16 Theme:T3
E9	Methylation Site:T16 Theme:T3
E10	Acetylation Theme:T3
E11	Methylation Site:T16 Theme:T3
E12	Methylation Site:T16 Theme:T3
E13	Acetylation Theme:T9
E14	Methylation Site:T16 Theme:T3
