T1	Protein	beta(2)-adrenergic receptor
T2	Protein	EGLN3
T3	Protein	pVHL
T5	Protein	beta(2)AR
T6	Protein	von Hippel-Lindau tumor suppressor
*	Equiv T1 T5
*	Equiv T3 T6
T25	Entity	proline-382
T26	Entity	-395
E1	Hydroxylation Theme:T5
E2	Catalysis Cause:T2 Theme:E1
E3	Ubiquitination Theme:T5
E4	Catalysis Cause:T6 Theme:E3
E5	Ubiquitination Theme:T5
E6	Ubiquitination Theme:T5
E7	Catalysis Cause:T2 Theme:E9
E8	Hydroxylation Site:T25 Theme:T5
E9	Hydroxylation Site:T26 Theme:T5
E10	Catalysis Cause:T2 Theme:E8
E11	Hydroxylation Theme:T5
E12	Ubiquitination Theme:T5
