T1	Protein	connexin-43
T2	Protein	Hrs
T3	Protein	Tsg101
T4	Protein	ubiquitin
T6	Protein	Cx43
T7	Protein	Gja1
T12	Protein	hepatocyte growth factor-regulated tyrosine kinase substrate
T13	Protein	Hgs
T15	Protein	tumor susceptibility gene 101
*	Equiv T1 T6 T7
*	Equiv T2 T12 T13
*	Equiv T3 T15
E1	Ubiquitination Theme:T1
E2	Ubiquitination Theme:T1
E3	Dephosphorylation Theme:T1
E4	Deubiquitination Theme:T1
E5	Phosphorylation Theme:T1
E6	Ubiquitination Theme:T1
E7	Ubiquitination Theme:T1
