T1	Protein	MUC1
*	Equiv T11 T12
*	Equiv T13 T14
*	Equiv T15 T16
T8	Entity	immunodominant region
T9	Entity	extracellular domain
T11	Entity	Tn
T12	Entity	GalNAc
T13	Entity	STn
T14	Entity	sialyl alpha2-6 GalNAc
T15	Entity	TF
T16	Entity	Gal beta1-3 GalNAc
T18	Entity	PDTRP core peptide epitope
E1	Glycosylation Site:T8 Theme:T1
E2	Glycosylation Sidechain:T11 Site:T9 Theme:T1
E3	Glycosylation Sidechain:T14 Site:T9 Theme:T1
E4	Glycosylation Sidechain:T15 Site:T9 Theme:T1
E5	Glycosylation Theme:T1
M1	Negation E5
E6	Glycosylation Site:T18 Theme:T1
E7	Glycosylation Theme:T1
