T1	Protein	H3
T2	Protein	H2B
T3	Protein	histone
T12	Protein	htb1
T15	Protein	ubiquitin
T16	Protein	Bre1
T22	Entity	K4
T23	Entity	K79
T24	Entity	K123
E1	Methylation Site:T22 Theme:T1
E2	Methylation Site:T23 Theme:T1
E3	Ubiquitination Site:T24 Theme:T2
E4	Methylation Site:T22 Theme:T1
E5	Methylation Site:T23 Theme:T1
E6	Ubiquitination Site:T24 Theme:T2
E7	Ubiquitination Theme:T2
M1	Negation E7
E8	Methylation Site:T23 Theme:T1
E9	Methylation Site:T22 Theme:T1
E10	Methylation Theme:T1
E11	Ubiquitination Theme:T2
E12	Methylation Theme:T1
E13	Methylation Theme:T1
M2	Negation E13
E14	Methylation Theme:T1
M3	Negation E14
E15	Methylation Theme:T1
