T1	Protein	calcitonin
T7	Entity	5' region
T9	Entity	25 CpG sites
T11	Entity	CpG sites
E1	DNA_methylation Theme:T1
E2	DNA_methylation Site:T7 Theme:T1
M1	Speculation E2
E3	DNA_methylation Site:T9 Theme:T1
M2	Speculation E3
E4	DNA_methylation Site:T11 Theme:T1
E5	DNA_methylation Site:T7 Theme:T1
E6	DNA_methylation Theme:T1
M3	Speculation E6
E7	DNA_methylation Theme:T1
E8	DNA_methylation Site:T11 Theme:T1
E9	DNA_methylation Theme:T1
