T1	Protein	prion proteins
T2	Protein	prion protein
T3	Protein	PrP
T5	Protein	PrPSc
T6	Protein	PrPC
T7	Protein	peptide N-glycosidase F
T8	Protein	PNGase F
T9	Protein	endoglycosidase H
T15	Protein	PrP 27-30
T22	Protein	lectins
T24	Protein	sialidase
*	Equiv T2 T3
*	Equiv T7 T8
T28	Entity	Asparagine
T32	Entity	Asn
T33	Entity	complex oligosaccharides
T36	Entity	oligosaccharide
E1	Glycosylation Site:T28 Theme:T1
E2	Deglycosylation Theme:T2
E3	Glycosylation Sidechain:T33 Site:T32 Theme:T15
M1	Speculation E3
E4	Glycosylation Sidechain:T36 Site:T32 Theme:T6
E5	Glycosylation Sidechain:T36 Site:T32 Theme:T5
