T1	Protein	factor VIIa
T2	Protein	coagulation factor VII
T4	Protein	factor X
T5	Protein	factor IX
T6	Protein	tissue factor
T21	Entity	aspartic acid residue
T23	Entity	asparagine residues
T24	Entity	Asparagine residues 145
T25	Entity	322
T27	Entity	asparagine residue 322
T29	Entity	asparagine residue 145
E1	Hydroxylation Site:T21 Theme:T1
E2	Glycosylation Site:T23 Theme:T1
E3	Glycosylation Site:T24 Theme:T1
E4	Glycosylation Site:T25 Theme:T1
E5	Glycosylation Site:T27 Theme:T1
E6	Glycosylation Site:T29 Theme:T1
