T1	Protein	histone H4
T2	Protein	histones
T3	Protein	H3
T4	Protein	histone
T5	Protein	SUV39H1
T6	Protein	Suv39h1
T10	Protein	H4
T14	Entity	lysine 20
T16	Entity	N-terminal region
T19	Entity	lysine 9
E1	Methylation Site:T14 Theme:T1
E2	Methylation Site:T16 Theme:T2
E3	Methylation Site:T19 Theme:T3
E4	Catalysis Cause:T5 Theme:E3
E5	Catalysis Cause:T6 Theme:E3
E6	Methylation Theme:T4
E7	Methylation Theme:T1
M1	Speculation E7
E8	Methylation Site:T14 Theme:T1
E9	Methylation Site:T14 Theme:T1
E10	Methylation Site:T14 Theme:T10
E11	Methylation Theme:T1
E12	Methylation Theme:T1
E13	Methylation Theme:T1
E14	Methylation Theme:T10
E15	Methylation Site:T14 Theme:T10
