T1	Protein	G9a
T2	Protein	histones
T3	Protein	histone H3
T11	Protein	EuHMT
T12	Protein	mAM
T14	Protein	H3
T20	Protein	HP1alpha
T21	Protein	HP1gamma
T23	Protein	histone
T27	Entity	lysine residues
T28	Entity	Lysine 9
T32	Entity	K239 residue
E1	Methylation Theme:T1
E2	Catalysis Cause:T1 Theme:E1
E3	Methylation Site:T27 Theme:T2
E4	Methylation Site:T28 Theme:T3
E5	Methylation Site:T32 Theme:T1
E6	Catalysis Cause:T1 Theme:E5
E7	Methylation Theme:T1
M1	Negation E7
E8	Catalysis Cause:T1 Theme:E7
E9	Catalysis Cause:T1 Theme:E10
E10	Methylation Theme:T1
