T1	Protein	Histone
T2	Protein	estrogen receptor alpha
T3	Protein	ER
T4	Protein	histone
T15	Protein	DNMT1
T16	Protein	HDAC1
T17	Protein	H3
T18	Protein	SUV39H 1
T20	Protein	histones H3
T21	Protein	H4
T23	Protein	HP1 alpha
*	Equiv T2 T3
T26	Entity	CpG island
T29	Entity	K9
T30	Entity	promoter
E1	DNA_demethylation Site:T26 Theme:T2
M1	Negation E1
E2	Acetylation Contextgene:T2 Theme:T20
E3	Acetylation Contextgene:T2 Theme:T21
E4	Methylation Contextgene:T2 Site:T29 Theme:T17
E5	DNA_methylation Site:T30 Theme:T2
