T1	Protein	histone H4
T3	Protein	histone
T4	Protein	H4
T21	Entity	Lys-5
T22	Entity	Lys-12
T31	Entity	lysine 12
E1	Acetylation Theme:T1
E2	Deacetylation Theme:T1
E3	Acetylation Theme:T1
E4	Acetylation Theme:T1
E5	Acetylation Theme:T3
E6	Acetylation Site:T21 Theme:T4
E7	Acetylation Site:T22 Theme:T4
E8	Acetylation Theme:T4
E9	Acetylation Theme:T4
M1	Speculation E9
E10	Acetylation Theme:T4
M2	Speculation E10
E11	Acetylation Theme:T4
E12	Acetylation Theme:T4
E13	Deacetylation Theme:T4
E14	Acetylation Theme:T4
E15	Acetylation Site:T31 Theme:T4
