T1	Protein	histone
T2	Protein	histones
T5	Protein	H3
T6	Protein	H4
T12	Entity	Lys 4
T13	Entity	Lys 79
E1	Acetylation Theme:T1
E2	Methylation Theme:T1
E3	Acetylation Theme:T5
E4	Acetylation Theme:T6
E5	Methylation Site:T12 Theme:T5
E6	Methylation Site:T13 Theme:T5
E7	Methylation Site:T12 Theme:T5
M1	Negation E7
E8	Methylation Site:T13 Theme:T5
M2	Negation E8
E9	Deacetylation Theme:T5
E10	Deacetylation Theme:T6
