T1	Organism	Photorhabdus luminescens
T2	Organism	Yersinia enterocolitica
T3	Organism	men
T4	Organism	Y. enterocolitica
T5	Organism	human
T6	Organism	P. luminescens
T7	Organism	Yersinia
T8	Organism	Y. pestis
T10	Organism	rat
T12	Organism	Y. pseudotuberculosis
T13	Organism	Y. pestis KIM
T26	Organism	Manduca sexta
T31	Organism	heterorhabditid nematodes
T32	Organism	Photorhabdus
T33	Organism	P. asymbiotica
T39	Organism	Heterorhabditis bacteriophora
T43	Protein	CipA
T44	Protein	CipB
E1	Process
E2	Process Participant:T1
E3	Process
E4	Process
E5	Process Participant:T32
E6	Process
E7	Gene_expression Theme:T43
E8	Gene_expression Theme:T44
E9	Process
E10	Process
