T1	Two-component-system	CsrS/R
T2	Protein	CsrS
T3	Protein	R
T4	Organism	GAS
T5	Organism	genetically- manipulated GAS
T6	Protein	csrS
T8	Organism	patients
T10	Protein	scpC
T11	Protein	slo
T13	Organism	invasive GAS
T18	Protein	csrR
T23	Protein	emm49
T32	Protein	emm
T33	Organism	human
T35	Organism	csrS mutant
T37	Organism	csrR mutant
T43	Protein	CsrR
T48	Protein	SpeB
T49	Protein	SLS
T50	Protein	speB
T51	Protein	sagA
T52	Organism	csrS-mutated severe invasive GAS
T56	Organism	non-invasive strains
T57	Organism	SLS-deletion in invasive GAS
T60	Protein	Extracellular deoxyribonuclease
T61	Protein	DNase
T62	Organism	emm1 type GAS
T63	Protein	emm1
T65	Chemical	PI
T68	Organism	emm49 severe invasive GAS
T70	Organism	non-invasive GAS
T74	Organism	emm1-genotype strains
T79	Protein	ScpC
T80	Protein	SLO
T87	Organism	scpC-deletion mutant
T91	Protein	IL-8
T96	Chemical	cholesterol
T111	Organism	mice
T112	Organism	csrS-mutated GAS
*	Equiv T60 T61
E1	Process Participant:T4
E2	Process Participant:T4
E3	Positive_regulation Theme:E5
E4	Positive_regulation Theme:E6
E5	Gene_expression Theme:T10
E6	Gene_expression Theme:T11
E7	Process
E8	Gene_expression Theme:T6
E9	Process Participant:T4
E10	Gene_expression Theme:T11
E11	Positive_regulation Theme:E10
E12	Process
E13	Process
E14	Process
E15	Gene_expression Theme:T50
E16	Gene_expression Theme:T51
E17	Positive_regulation Theme:E15
M1	Negation E17
E18	Positive_regulation Theme:E16
M2	Negation E18
E19	Process
E20	Gene_expression Theme:T60
E21	Gene_expression Theme:T11
E22	Gene_expression Theme:T10
E23	Positive_regulation Theme:E20
E24	Positive_regulation Theme:E21
E25	Positive_regulation Theme:E22
E26	Process
E27	Positive_regulation Theme:E29
E28	Positive_regulation Theme:E30
E29	Gene_expression Theme:T79
E30	Gene_expression Theme:T80
E31	Process Participant:T4
E32	Process
E33	Process
E34	Regulation Theme:T6
E35	Process Participant:T112
E36	Process Participant:T13
E37	Process Participant:T13
E38	Process Participant:T13
E39	Process Participant:T13
E40	Process Participant:T13
E41	Process
E42	Process
E43	Process
