T1	Organism	Streptococcus equi subspeices equi
T2	Organism	S. equi
T3	Organism	equine
T4	Organism	horses
T6	Organism	horse
T7	Organism	Horses
T12	Organism	group A Streptococcus
T13	Organism	GAS
T14	Chemical	hyaluronic acid
T15	Protein	M protein
T17	Protein	Mac
T18	Protein	IdeE
T20	Organism	human
T22	Protein	immunoglobulin G
T23	Protein	IgG
T27	Protein	Fc receptor
T30	Organism	serotype M1 GAS
T37	Protein	SeMac
T40	Protein	cysteine endopeptidase
*	Equiv T1 T2
*	Equiv T12 T13
*	Equiv T18 T17
*	Equiv T22 T23
E1	Process
E2	Process
E3	Process
E4	Process Participant:T1
E5	Gene_expression Theme:T15
E6	Process
E7	Gene_expression Theme:T17
E8	Localization Theme:T17
E9	Positive_regulation Cause:T17 Theme:E10
E10	Protein_catabolism Theme:T22
E11	Gene_expression Theme:T17
E12	Negative_regulation Theme:E13
E13	Binding Theme1:T22 Theme2:T27
E14	Gene_expression Theme:T17
E15	Binding Theme1:T17 Theme2:T27
E16	Process Participant:T1
