T1	Organism	Pseudomonas aeruginosa
T3	Organism	P. aeruginosa
T4	Chemical	lipopolysaccharide
T5	Chemical	LPS
T6	Two-component-system	PhoPQ
T7	Protein	PhoP
T8	Protein	Q
T9	Two-component-system	PmrAB
T10	Protein	PmrA
T11	Protein	B
T12	Regulon-operon	PA3552-PA3559
T13	Protein	PA3552
T14	Protein	PA3559
T16	Chemical	aminoglycosides
T17	Chemical	beta-lactam
T18	Chemical	fluoroquinolone
*	Equiv T4 T5
E1	Process Participant:T1
E2	Process
E3	Positive_regulation Theme:T12
E4	Regulation Cause:T6 Theme:T12
E5	Regulation Cause:T9 Theme:T12
E6	Process Participant:T3
E7	Gene_expression Theme:T12
E8	Positive_regulation Theme:E9
E9	Process
E10	Positive_regulation Theme:E11
E11	Process
E12	Regulation Theme:E13
M1	Negation E12
E13	Process
E14	Process
E15	Process
