T1	Organism	Brucella abortus
T2	Two-component-system	BvrR/BvrS
T3	Protein	BvrR
T4	Protein	BvrS
T9	Chemical	lipid A
T13	Organism	B. abortus
T14	Organism	bvrR mutant
T15	Protein	bvrR
T18	Protein	omp25a
T19	Protein	omp25d
T20	Chemical	LPS
T21	Chemical	fatty acid
T22	Chemical	carbon
T23	Protein	pckA
T24	Protein	fumB
T27	Protein	nirK
T28	Protein	norC
T29	Protein	nosZ
T30	Protein	VjbR
T31	Protein	ExoR
T32	Protein	OmpR
T35	Organism	Brucella
T40	Chemical	nitrogen
E1	Positive_regulation Cause:T2 Theme:E2
E2	Process Participant:T1
E3	Gene_expression Theme:T18
E4	Gene_expression Theme:T19
E5	Positive_regulation Theme:T23
E6	Positive_regulation Theme:T24
E7	Regulation Theme:T27
E8	Regulation Theme:T28
E9	Regulation Theme:T29
E10	Regulation Theme:T30
E11	Regulation Theme:T31
E12	Regulation Theme:T32
E13	Gene_expression Theme:T30
E14	Gene_expression Theme:T31
E15	Gene_expression Theme:T32
E16	Process Participant:T35
